/**
 * Top ATP/WTA players (Option A — hardcoded fallback).
 * 
 * Généré depuis tennis-Player-Photos.json (93 joueurs).
 * Rangs ATP approximés (juillet 2026).
 * Pays devinés depuis le nom de famille (à raffiner).
 */

import type { PlayerResult } from "./tennis-Search-Types";

export const TOP_PLAYERS: PlayerResult[] = [
  {
    id: "ajla_tomljanovic",
    name: "Ajla Tomljanovic",
    slug: "ajla_tomljanovic",
    rank: 100,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ajla_Tomljanovic_2022.jpg/220px-Ajla_Tomljanovic_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "alejandro_davidovich_fokina",
    name: "Alejandro Davidovich Fokina",
    slug: "alejandro_davidovich_fokina",
    rank: 101,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ADFOKINA.jpg",
    circuit: "ATP",
  },
  {
    id: "alex_de_minaur",
    name: "Alex De Minaur",
    slug: "alex_de_minaur",
    rank: 16,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/DEMINAUR.jpg",
    circuit: "ATP",
  },
  {
    id: "alexander_zverev",
    name: "Alexander Zverev",
    slug: "alexander_zverev",
    rank: 4,
    country: "DE",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/AZVEREV.jpg",
    circuit: "ATP",
  },
  {
    id: "alexandra_eala",
    name: "Alexandra Eala",
    slug: "alexandra_eala",
    rank: 102,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ALEXANEALA.jpg",
    circuit: "ATP",
  },
  {
    id: "amanda_anisimova",
    name: "Amanda Anisimova",
    slug: "amanda_anisimova",
    rank: 103,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ANISIMOVA.jpg",
    circuit: "ATP",
  },
  {
    id: "andrey_rublev",
    name: "Andrey Rublev",
    slug: "andrey_rublev",
    rank: 7,
    country: "RU",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ARUBLEV.jpg",
    circuit: "ATP",
  },
  {
    id: "anett_kontaveit",
    name: "Anett Kontaveit",
    slug: "anett_kontaveit",
    rank: 104,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Anett_Kontaveit_2022.jpg/220px-Anett_Kontaveit_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "angelique_kerber",
    name: "Angelique Kerber",
    slug: "angelique_kerber",
    rank: 105,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Angelique_Kerber_2019.jpg/220px-Angelique_Kerber_2019.jpg",
    circuit: "ATP",
  },
  {
    id: "anna_kalinskaya",
    name: "Anna Kalinskaya",
    slug: "anna_kalinskaya",
    rank: 106,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/AKALINSKAYA.jpg",
    circuit: "ATP",
  },
  {
    id: "arthur_fils",
    name: "Arthur Fils",
    slug: "arthur_fils",
    rank: 18,
    country: "FR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ARTHURFILS.jpg",
    circuit: "ATP",
  },
  {
    id: "aryna_sabalenka",
    name: "Aryna Sabalenka",
    slug: "aryna_sabalenka",
    rank: 107,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/SABALENKA.jpg",
    circuit: "ATP",
  },
  {
    id: "asia_muhammad",
    name: "Asia Muhammad",
    slug: "asia_muhammad",
    rank: 108,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/AMUHAMMAD.jpg",
    circuit: "ATP",
  },
  {
    id: "barbora_krejcikova",
    name: "Barbora Krejcikova",
    slug: "barbora_krejcikova",
    rank: 109,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/BKREJCIKOVA.jpg",
    circuit: "ATP",
  },
  {
    id: "beatriz_haddad_maia",
    name: "Beatriz Haddad Maia",
    slug: "beatriz_haddad_maia",
    rank: 110,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/HADDADMA.jpg",
    circuit: "ATP",
  },
  {
    id: "belinda_bencic",
    name: "Belinda Bencic",
    slug: "belinda_bencic",
    rank: 111,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/BBENCIC.jpg",
    circuit: "ATP",
  },
  {
    id: "bethanie_mattek_sands",
    name: "Bethanie Mattek-Sands",
    slug: "bethanie_mattek_sands",
    rank: 112,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MATSANDS.jpg",
    circuit: "ATP",
  },
  {
    id: "bianca_andreescu",
    name: "Bianca Andreescu",
    slug: "bianca_andreescu",
    rank: 113,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/BANDREESCU.jpg",
    circuit: "ATP",
  },
  {
    id: "borna_coric",
    name: "Borna Coric",
    slug: "borna_coric",
    rank: 35,
    country: "HR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/CORIC.jpg",
    circuit: "ATP",
  },
  {
    id: "carlos_alcaraz",
    name: "Carlos Alcaraz",
    slug: "carlos_alcaraz",
    rank: 2,
    country: "ES",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/CALCARAZ.jpg",
    circuit: "ATP",
  },
  {
    id: "caroline_garcia",
    name: "Caroline Garcia",
    slug: "caroline_garcia",
    rank: 114,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Caroline_Garcia_2018.jpg/220px-Caroline_Garcia_2018.jpg",
    circuit: "ATP",
  },
  {
    id: "casper_ruud",
    name: "Casper Ruud",
    slug: "casper_ruud",
    rank: 10,
    country: "NO",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/CASPRUUD.jpg",
    circuit: "ATP",
  },
  {
    id: "catherine_mcnally",
    name: "Catherine Mcnally",
    slug: "catherine_mcnally",
    rank: 115,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Catherine_McNally_2021.jpg/220px-Catherine_McNally_2021.jpg",
    circuit: "ATP",
  },
  {
    id: "coco_gauff",
    name: "Coco Gauff",
    slug: "coco_gauff",
    rank: 116,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/CGAUFF.jpg",
    circuit: "ATP",
  },
  {
    id: "danielle_collins",
    name: "Danielle Collins",
    slug: "danielle_collins",
    rank: 117,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/DCOLLINS.jpg",
    circuit: "ATP",
  },
  {
    id: "daniil_medvedev",
    name: "Daniil Medvedev",
    slug: "daniil_medvedev",
    rank: 5,
    country: "RU",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/DMEDVEDEV.jpg",
    circuit: "ATP",
  },
  {
    id: "daria_kasatkina",
    name: "Daria Kasatkina",
    slug: "daria_kasatkina",
    rank: 118,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/DKASAT.jpg",
    circuit: "ATP",
  },
  {
    id: "david_goffin",
    name: "David Goffin",
    slug: "david_goffin",
    rank: 25,
    country: "BE",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/DGOFFIN.jpg",
    circuit: "ATP",
  },
  {
    id: "desirae_krawczyk",
    name: "Desirae Krawczyk",
    slug: "desirae_krawczyk",
    rank: 119,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/DKRAWCZYK.jpg",
    circuit: "ATP",
  },
  {
    id: "ekaterina_alexandrova",
    name: "Ekaterina Alexandrova",
    slug: "ekaterina_alexandrova",
    rank: 120,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/EALEXANDRO.jpg",
    circuit: "ATP",
  },
  {
    id: "elena_rybakina",
    name: "Elena Rybakina",
    slug: "elena_rybakina",
    rank: 121,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Elena_Rybakina_2023.jpg/220px-Elena_Rybakina_2023.jpg",
    circuit: "ATP",
  },
  {
    id: "elina_svitolina",
    name: "Elina Svitolina",
    slug: "elina_svitolina",
    rank: 122,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Elina_Svitolina_2021.jpg/220px-Elina_Svitolina_2021.jpg",
    circuit: "ATP",
  },
  {
    id: "elise_mertens",
    name: "Elise Mertens",
    slug: "elise_mertens",
    rank: 123,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/EMERTENS.jpg",
    circuit: "ATP",
  },
  {
    id: "emma_navarro",
    name: "Emma Navarro",
    slug: "emma_navarro",
    rank: 124,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/EMNAVARRO.jpg",
    circuit: "ATP",
  },
  {
    id: "felix_auger_aliassime",
    name: "Felix Auger-Aliassime",
    slug: "felix_auger_aliassime",
    rank: 12,
    country: "CA",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/FAUGER.jpg",
    circuit: "ATP",
  },
  {
    id: "flavio_cobolli",
    name: "Flavio Cobolli",
    slug: "flavio_cobolli",
    rank: 22,
    country: "IT",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/FLACOBOLLI.jpg",
    circuit: "ATP",
  },
  {
    id: "francisco_cerundolo",
    name: "Francisco Cerundolo",
    slug: "francisco_cerundolo",
    rank: 15,
    country: "AR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/FCERUNDO.jpg",
    circuit: "ATP",
  },
  {
    id: "garbine_muguruza",
    name: "Garbine Muguruza",
    slug: "garbine_muguruza",
    rank: 125,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Garbine_Muguruza_2019.jpg/220px-Garbine_Muguruza_2019.jpg",
    circuit: "ATP",
  },
  {
    id: "grigor_dimitrov",
    name: "Grigor Dimitrov",
    slug: "grigor_dimitrov",
    rank: 17,
    country: "BG",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/GDIMITROV.jpg",
    circuit: "ATP",
  },
  {
    id: "holger_rune",
    name: "Holger Rune",
    slug: "holger_rune",
    rank: 6,
    country: "DK",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/HOLRUNE.jpg",
    circuit: "ATP",
  },
  {
    id: "hubert_hurkacz",
    name: "Hubert Hurkacz",
    slug: "hubert_hurkacz",
    rank: 126,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/HURKACZ.jpg",
    circuit: "ATP",
  },
  {
    id: "iga_swiatek",
    name: "Iga Swiatek",
    slug: "iga_swiatek",
    rank: 127,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ISWIATEK.jpg",
    circuit: "ATP",
  },
  {
    id: "iva_jovic",
    name: "Iva Jovic",
    slug: "iva_jovic",
    rank: 128,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/IVAJOVIC.jpg",
    circuit: "ATP",
  },
  {
    id: "jack_draper",
    name: "Jack Draper",
    slug: "jack_draper",
    rank: 9,
    country: "GB",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JDRAPER.jpg",
    circuit: "ATP",
  },
  {
    id: "jannik_sinner",
    name: "Jannik Sinner",
    slug: "jannik_sinner",
    rank: 1,
    country: "IT",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JSINNER.jpg",
    circuit: "ATP",
  },
  {
    id: "jasmine_paolini",
    name: "Jasmine Paolini",
    slug: "jasmine_paolini",
    rank: 129,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JASPAOLINI.jpg",
    circuit: "ATP",
  },
  {
    id: "jelena_ostapenko",
    name: "Jelena Ostapenko",
    slug: "jelena_ostapenko",
    rank: 130,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Jelena_Ostapenko_2017.jpg/220px-Jelena_Ostapenko_2017.jpg",
    circuit: "ATP",
  },
  {
    id: "jenson_brooksby",
    name: "Jenson Brooksby",
    slug: "jenson_brooksby",
    rank: 131,
    country: "US",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JBROOKSBY.jpg",
    circuit: "ATP",
  },
  {
    id: "jessica_pegula",
    name: "Jessica Pegula",
    slug: "jessica_pegula",
    rank: 132,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JPEGULA.jpg",
    circuit: "ATP",
  },
  {
    id: "jiri_lehecka",
    name: "Jiri Lehecka",
    slug: "jiri_lehecka",
    rank: 133,
    country: "CZ",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JIRILEHECKA.jpg",
    circuit: "ATP",
  },
  {
    id: "joao_fonseca",
    name: "Joao Fonseca",
    slug: "joao_fonseca",
    rank: 19,
    country: "BR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/JOAOFONSECA.jpg",
    circuit: "ATP",
  },
  {
    id: "karen_khachanov",
    name: "Karen Khachanov",
    slug: "karen_khachanov",
    rank: 134,
    country: "RU",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/KKHACHANOV.jpg",
    circuit: "ATP",
  },
  {
    id: "karolina_muchova",
    name: "Karolina Muchova",
    slug: "karolina_muchova",
    rank: 135,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MUCHOVA.jpg",
    circuit: "ATP",
  },
  {
    id: "karolina_pliskova",
    name: "Karolina Pliskova",
    slug: "karolina_pliskova",
    rank: 136,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Karolina_Pliskova_2019.jpg/220px-Karolina_Pliskova_2019.jpg",
    circuit: "ATP",
  },
  {
    id: "katie_boulter",
    name: "Katie Boulter",
    slug: "katie_boulter",
    rank: 137,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/KBOULTER.jpg",
    circuit: "ATP",
  },
  {
    id: "leylah_fernandez",
    name: "Leylah Fernandez",
    slug: "leylah_fernandez",
    rank: 138,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/LFERNAND.jpg",
    circuit: "ATP",
  },
  {
    id: "liudmila_samsonova",
    name: "Liudmila Samsonova",
    slug: "liudmila_samsonova",
    rank: 139,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Liudmila_Samsonova_2022.jpg/220px-Liudmila_Samsonova_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "madison_keys",
    name: "Madison Keys",
    slug: "madison_keys",
    rank: 140,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MADKEYS.jpg",
    circuit: "ATP",
  },
  {
    id: "maja_chwalinska",
    name: "Maja Chwalinska",
    slug: "maja_chwalinska",
    rank: 141,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MCHWALINSK.jpg",
    circuit: "ATP",
  },
  {
    id: "marcos_giron",
    name: "Marcos Giron",
    slug: "marcos_giron",
    rank: 142,
    country: "US",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MARCGIRON.jpg",
    circuit: "ATP",
  },
  {
    id: "maria_sakkari",
    name: "Maria Sakkari",
    slug: "maria_sakkari",
    rank: 143,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/SAKKARI.jpg",
    circuit: "ATP",
  },
  {
    id: "maria_sakkari2",
    name: "Maria Sakkari2",
    slug: "maria_sakkari2",
    rank: 144,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Maria_Sakkari_2022.jpg/220px-Maria_Sakkari_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "marin_cilic",
    name: "Marin Cilic",
    slug: "marin_cilic",
    rank: 30,
    country: "HR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MCILIC.jpg",
    circuit: "ATP",
  },
  {
    id: "marketa_vondrousova",
    name: "Marketa Vondrousova",
    slug: "marketa_vondrousova",
    rank: 145,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Marketa_Vondrousova_2023.jpg/220px-Marketa_Vondrousova_2023.jpg",
    circuit: "ATP",
  },
  {
    id: "marta_kostyuk",
    name: "Marta Kostyuk",
    slug: "marta_kostyuk",
    rank: 146,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MKOSTYUK.jpg",
    circuit: "ATP",
  },
  {
    id: "martina_trevisan",
    name: "Martina Trevisan",
    slug: "martina_trevisan",
    rank: 147,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Martina_Trevisan_2022.jpg/220px-Martina_Trevisan_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "matteo_arnaldi",
    name: "Matteo Arnaldi",
    slug: "matteo_arnaldi",
    rank: 11,
    country: "IT",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MATARNALDI.jpg",
    circuit: "ATP",
  },
  {
    id: "matteo_berrettini",
    name: "Matteo Berrettini",
    slug: "matteo_berrettini",
    rank: 14,
    country: "IT",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MBERRETT.jpg",
    circuit: "ATP",
  },
  {
    id: "miomir_kecmanovic",
    name: "Miomir Kecmanovic",
    slug: "miomir_kecmanovic",
    rank: 148,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/KECMANOVIC.jpg",
    circuit: "ATP",
  },
  {
    id: "mirra_andreeva",
    name: "Mirra Andreeva",
    slug: "mirra_andreeva",
    rank: 149,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/MANDREEVA.jpg",
    circuit: "ATP",
  },
  {
    id: "naomi_osaka",
    name: "Naomi Osaka",
    slug: "naomi_osaka",
    rank: 150,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/NOSAKA.jpg",
    circuit: "ATP",
  },
  {
    id: "nick_kyrgios",
    name: "Nick Kyrgios",
    slug: "nick_kyrgios",
    rank: 151,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/KYRGIOS.jpg",
    circuit: "ATP",
  },
  {
    id: "novak_djokovic",
    name: "Novak Djokovic",
    slug: "novak_djokovic",
    rank: 3,
    country: "RS",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/NDJOKOVIC.jpg",
    circuit: "ATP",
  },
  {
    id: "ons_jabeur",
    name: "Ons Jabeur",
    slug: "ons_jabeur",
    rank: 152,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/ONSJABEUR.jpg",
    circuit: "ATP",
  },
  {
    id: "paula_badosa",
    name: "Paula Badosa",
    slug: "paula_badosa",
    rank: 153,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/PBADOSA.jpg",
    circuit: "ATP",
  },
  {
    id: "petra_kvitova",
    name: "Petra Kvitova",
    slug: "petra_kvitova",
    rank: 154,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Petra_Kvitova_2019.jpg/220px-Petra_Kvitova_2019.jpg",
    circuit: "ATP",
  },
  {
    id: "roberto_bautista_agut",
    name: "Roberto Bautista Agut",
    slug: "roberto_bautista_agut",
    rank: 155,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/BAUTAGU.jpg",
    circuit: "ATP",
  },
  {
    id: "roger_federer",
    name: "Roger Federer",
    slug: "roger_federer",
    rank: 999,
    country: "CH",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/RFEDERER.jpg",
    circuit: "ATP",
  },
  {
    id: "sebastian_baez",
    name: "Sebastian Baez",
    slug: "sebastian_baez",
    rank: 13,
    country: "AR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/SEBASBAEZ.jpg",
    circuit: "ATP",
  },
  {
    id: "sebastian_korda",
    name: "Sebastian Korda",
    slug: "sebastian_korda",
    rank: 156,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/SEBKORDA.jpg",
    circuit: "ATP",
  },
  {
    id: "serena_williams",
    name: "Serena Williams",
    slug: "serena_williams",
    rank: 157,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Serena_Williams_2013_US_Open.jpg/220px-Serena_Williams_2013_US_Open.jpg",
    circuit: "ATP",
  },
  {
    id: "shuai_zhang",
    name: "Shuai Zhang",
    slug: "shuai_zhang",
    rank: 158,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Zhang_Shuai_2022.jpg/220px-Zhang_Shuai_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "simona_halep",
    name: "Simona Halep",
    slug: "simona_halep",
    rank: 159,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Simona_Halep_2022.jpg/220px-Simona_Halep_2022.jpg",
    circuit: "ATP",
  },
  {
    id: "sofia_kenin",
    name: "Sofia Kenin",
    slug: "sofia_kenin",
    rank: 160,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/SKENIN.jpg",
    circuit: "ATP",
  },
  {
    id: "sorana_cirstea",
    name: "Sorana Cirstea",
    slug: "sorana_cirstea",
    rank: 161,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/SCIRSTEA.jpg",
    circuit: "ATP",
  },
  {
    id: "tallon_griekspoor",
    name: "Tallon Griekspoor",
    slug: "tallon_griekspoor",
    rank: 162,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/TGRIEKSPOOR.jpg",
    circuit: "ATP",
  },
  {
    id: "taylor_fritz",
    name: "Taylor Fritz",
    slug: "taylor_fritz",
    rank: 8,
    country: "US",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/TFRITZ.jpg",
    circuit: "ATP",
  },
  {
    id: "tomas_martin_etcheverry",
    name: "Tomas Martin Etcheverry",
    slug: "tomas_martin_etcheverry",
    rank: 20,
    country: "AR",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/TMETCHEVER.jpg",
    circuit: "ATP",
  },
  {
    id: "venus_williams",
    name: "Venus Williams",
    slug: "venus_williams",
    rank: 163,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Venus_Williams_2018_Wimbledon.jpg/220px-Venus_Williams_2018_Wimbledon.jpg",
    circuit: "ATP",
  },
  {
    id: "veronika_kudermetova",
    name: "Veronika Kudermetova",
    slug: "veronika_kudermetova",
    rank: 164,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/VKUDERMET.jpg",
    circuit: "ATP",
  },
  {
    id: "victoria_azarenka",
    name: "Victoria Azarenka",
    slug: "victoria_azarenka",
    rank: 165,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Victoria_Azarenka_2020.jpg/220px-Victoria_Azarenka_2020.jpg",
    circuit: "ATP",
  },
  {
    id: "victoria_mboko",
    name: "Victoria Mboko",
    slug: "victoria_mboko",
    rank: 166,
    country: "XX",
    photoUrl: "https://img.tennis-Warehouse.com/graphics-Resizer/headshots/VICKYMBOKO.jpg",
    circuit: "ATP",
  },
  {
    id: "zhu_lin",
    name: "Zhu Lin",
    slug: "zhu_lin",
    rank: 167,
    country: "XX",
    photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Zhu_Lin_2023.jpg/220px-Zhu_Lin_2023.jpg",
    circuit: "ATP",
  },
];

/**
 * Recherche fuzzy sur les joueurs (prefix + contains).
 * Insensible à la casse et aux accents.
 */
export function searchPlayers(query: string, limit = 10): PlayerResult[] {
  const q = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();
  if (q.length < 2) return [];
  return TOP_PLAYERS
    .filter(p => {
      const n = p.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      return n.includes(q);
    })
    .sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999))
    .slice(0, limit);
}
