/**
 * Top ATP/WTA tournaments (Option A — hardcoded fallback).
 *
 * Source : calendars officiels ATP/WTA 2026 ( Grand Slams + Masters 1000 +
 * ATP 500 + ATP 250 principaux + équivalents WTA ).
 *
 * Slugs utilisés dans l'URL /tennis/tournament/[slug].
 */

import type { TournamentResult } from "./tennis-search-types";

export const KNOWN_TOURNAMENTS: TournamentResult[] = [
  // ─── Grand Slams (4) ────────────────────────────────────────────────────
  {
    id: "australian-open",
    name: "Australian Open",
    slug: "australian-open",
    surface: "Dur",
    country: "AU",
    city: "Melbourne",
    category: "Grand Slam",
  },
  {
    id: "roland-garros",
    name: "Roland-Garros",
    slug: "roland-garros",
    surface: "Terre",
    country: "FR",
    city: "Paris",
    category: "Grand Slam",
  },
  {
    id: "wimbledon",
    name: "Wimbledon",
    slug: "wimbledon",
    surface: "Gazon",
    country: "GB",
    city: "Londres",
    category: "Grand Slam",
  },
  {
    id: "us-open",
    name: "US Open",
    slug: "us-open",
    surface: "Dur",
    country: "US",
    city: "New York",
    category: "Grand Slam",
  },

  // ─── ATP Masters 1000 (9) ───────────────────────────────────────────────
  {
    id: "indian-wells",
    name: "Indian Wells",
    slug: "indian-wells",
    surface: "Dur",
    country: "US",
    city: "Indian Wells",
    category: "ATP Masters 1000",
  },
  {
    id: "miami-open",
    name: "Miami Open",
    slug: "miami-open",
    surface: "Dur",
    country: "US",
    city: "Miami",
    category: "ATP Masters 1000",
  },
  {
    id: "monte-carlo",
    name: "Monte-Carlo",
    slug: "monte-carlo",
    surface: "Terre",
    country: "MC",
    city: "Roquebrune-Cap-Martin",
    category: "ATP Masters 1000",
  },
  {
    id: "madrid-open",
    name: "Mutua Madrid Open",
    slug: "madrid-open",
    surface: "Terre",
    country: "ES",
    city: "Madrid",
    category: "ATP Masters 1000",
  },
  {
    id: "internazionali-bnl-ditalia",
    name: "Internazionali BNL d'Italia",
    slug: "internazionali-bnl-ditalia",
    surface: "Terre",
    country: "IT",
    city: "Rome",
    category: "ATP Masters 1000",
  },
  {
    id: "cincinnati-open",
    name: "Cincinnati Open",
    slug: "cincinnati-open",
    surface: "Dur",
    country: "US",
    city: "Cincinnati",
    category: "ATP Masters 1000",
  },
  {
    id: "shanghai-masters",
    name: "Shanghai Masters",
    slug: "shanghai-masters",
    surface: "Dur",
    country: "CN",
    city: "Shanghai",
    category: "ATP Masters 1000",
  },
  {
    id: "paris-masters",
    name: "Rolex Paris Masters",
    slug: "paris-masters",
    surface: "Dur",
    country: "FR",
    city: "Paris",
    category: "ATP Masters 1000",
  },
  {
    id: "national-bank-open",
    name: "National Bank Open",
    slug: "national-bank-open",
    surface: "Dur",
    country: "CA",
    city: "Toronto / Montréal",
    category: "ATP Masters 1000",
  },

  // ─── ATP Finals (1) ─────────────────────────────────────────────────────
  {
    id: "atp-finals",
    name: "ATP Finals",
    slug: "atp-finals",
    surface: "Dur",
    country: "IT",
    city: "Turin",
    category: "ATP Finals",
  },

  // ─── ATP 500 (13 principaux) ────────────────────────────────────────────
  {
    id: "rotterdam",
    name: "ABN AMRO Open",
    slug: "rotterdam",
    surface: "Dur",
    country: "NL",
    city: "Rotterdam",
    category: "ATP 500",
  },
  {
    id: "acapulco",
    name: "Mexican Open",
    slug: "acapulco",
    surface: "Dur",
    country: "MX",
    city: "Acapulco",
    category: "ATP 500",
  },
  {
    id: "dubai-duty-free",
    name: "Dubai Duty Free Tennis",
    slug: "dubai-duty-free",
    surface: "Dur",
    country: "AE",
    city: "Dubai",
    category: "ATP 500",
  },
  {
    id: "barcelona-open",
    name: "Barcelona Open",
    slug: "barcelona-open",
    surface: "Terre",
    country: "ES",
    city: "Barcelone",
    category: "ATP 500",
  },
  {
    id: "hapag-lloyd-halle",
    name: "Halle Open",
    slug: "hapag-lloyd-halle",
    surface: "Gazon",
    country: "DE",
    city: "Halle",
    category: "ATP 500",
  },
  {
    id: "queen-s-club",
    name: "Queen's Club Championships",
    slug: "queen-s-club",
    surface: "Gazon",
    country: "GB",
    city: "Londres",
    category: "ATP 500",
  },
  {
    id: "hurst-hamburg",
    name: "Hamburg Open",
    slug: "hurst-hamburg",
    surface: "Terre",
    country: "DE",
    city: "Hambourg",
    category: "ATP 500",
  },
  {
    id: "cerrado-master-vienna",
    name: "Vienna Open",
    slug: "cerrado-master-vienna",
    surface: "Dur",
    country: "AT",
    city: "Vienne",
    category: "ATP 500",
  },
  {
    id: "swiss-indoors",
    name: "Swiss Indoors",
    slug: "swiss-indoors",
    surface: "Dur",
    country: "CH",
    city: "Bâle",
    category: "ATP 500",
  },
  {
    id: "rio-open",
    name: "Rio Open",
    slug: "rio-open",
    surface: "Terre",
    country: "BR",
    city: "Rio de Janeiro",
    category: "ATP 500",
  },
  {
    id: "toray-pan-pacific",
    name: "Toray Pan Pacific Open",
    slug: "toray-pan-pacific",
    surface: "Dur",
    country: "JP",
    city: "Tokyo",
    category: "ATP 500",
  },
  {
    id: "china-open",
    name: "China Open",
    slug: "china-open",
    surface: "Dur",
    country: "CN",
    city: "Pékin",
    category: "ATP 500",
  },
  {
    id: "astana-open",
    name: "Astana Open",
    slug: "astana-open",
    surface: "Dur",
    country: "KZ",
    city: "Astana",
    category: "ATP 500",
  },

  // ─── ATP 250 — sélection (38 tournois, principaux) ─────────────────────
  {
    id: "brisbane-international",
    name: "Brisbane International",
    slug: "brisbane-international",
    surface: "Dur",
    country: "AU",
    city: "Brisbane",
    category: "ATP 250",
  },
  {
    id: "united-cup",
    name: "United Cup",
    slug: "united-cup",
    surface: "Dur",
    country: "AU",
    city: "Perth / Sydney",
    category: "ATP 250",
  },
  {
    id: "adelaide-international",
    name: "Adelaide International",
    slug: "adelaide-international",
    surface: "Dur",
    country: "AU",
    city: "Adelaide",
    category: "ATP 250",
  },
  {
    id: "asb-classic",
    name: "ASB Classic",
    slug: "asb-classic",
    surface: "Dur",
    country: "NZ",
    city: "Auckland",
    category: "ATP 250",
  },
  {
    id: "qatar-exxonmobil-open",
    name: "Qatar ExxonMobil Open",
    slug: "qatar-exxonmobil-open",
    surface: "Dur",
    country: "QA",
    city: "Doha",
    category: "ATP 250",
  },
  {
    id: "open-provence",
    name: "Open 13 Provence",
    slug: "open-provence",
    surface: "Dur",
    country: "FR",
    city: "Marseille",
    category: "ATP 250",
  },
  {
    id: "delray-beach",
    name: "Delray Beach Open",
    slug: "delray-beach",
    surface: "Dur",
    country: "US",
    city: "Delray Beach",
    category: "ATP 250",
  },
  {
    id: "aberto-brasil-de-tennis",
    name: "Brasil Open",
    slug: "aberto-brasil-de-tennis",
    surface: "Terre",
    country: "BR",
    city: "São Paulo",
    category: "ATP 250",
  },
  {
    id: "Argentina-open",
    name: "Argentina Open",
    slug: "Argentina-open",
    surface: "Terre",
    country: "AR",
    city: "Buenos Aires",
    category: "ATP 250",
  },
  {
    id: "dallas-open",
    name: "Dallas Open",
    slug: "dallas-open",
    surface: "Dur",
    country: "US",
    city: "Dallas",
    category: "ATP 250",
  },
  {
    id: "open-sud-de-france",
    name: "Open Sud de France",
    slug: "open-sud-de-france",
    surface: "Dur",
    country: "FR",
    city: "Montpellier",
    category: "ATP 250",
  },
  {
    id: "movistar-open",
    name: "Chile Open",
    slug: "movistar-open",
    surface: "Terre",
    country: "CL",
    city: "Santiago",
    category: "ATP 250",
  },
  {
    id: "cocoran-houston",
    name: "U.S. Men's Clay Court",
    slug: "cocoran-houston",
    surface: "Terre",
    country: "US",
    city: "Houston",
    category: "ATP 250",
  },
  {
    id: "grand-prix-hassan-ii",
    name: "Grand Prix Hassan II",
    slug: "grand-prix-hassan-ii",
    surface: "Terre",
    country: "MA",
    city: "Marrakech",
    category: "ATP 250",
  },
  {
    id: "banco-sarabia",
    name: "Estoril Open",
    slug: "banco-sarabia",
    surface: "Terre",
    country: "PT",
    city: "Estoril",
    category: "ATP 250",
  },
  {
    id: " BMW-open-munich",
    name: "BMW Open",
    slug: " BMW-open-munich",
    surface: "Terre",
    country: "DE",
    city: "Munich",
    category: "ATP 250",
  },
  {
    id: "madrid-masters-madrid",
    name: "Mutua Madrid Open",
    slug: "madrid-masters-madrid",
    surface: "Terre",
    country: "ES",
    city: "Madrid",
    category: "ATP 250",
  },
  {
    id: "open-de-rouen",
    name: "Open de Rouen",
    slug: "open-de-rouen",
    surface: "Terre",
    country: "FR",
    city: "Rouen",
    category: "ATP 250",
  },
  {
    id: "turkish-open",
    name: "Turkish Open",
    slug: "turkish-open",
    surface: "Terre",
    country: "TR",
    city: "Antalya",
    category: "ATP 250",
  },
  {
    id: "geneva-open",
    name: "Gonet Geneva Open",
    slug: "geneva-open",
    surface: "Terre",
    country: "CH",
    city: "Genève",
    category: "ATP 250",
  },
  {
    id: " emilia-romagna-open",
    name: "Emilia-Romagna Open",
    slug: " emilia-romagna-open",
    surface: "Terre",
    country: "IT",
    city: "Bologne",
    category: "ATP 250",
  },
  {
    id: "olibia-open",
    name: "Lyon Open",
    slug: "olibia-open",
    surface: "Terre",
    country: "FR",
    city: "Lyon",
    category: "ATP 250",
  },
  {
    id: "stuttgart-open",
    name: "Boss Open",
    slug: "stuttgart-open",
    surface: "Gazon",
    country: "DE",
    city: "Stuttgart",
    category: "ATP 250",
  },
  {
    id: "libema-open",
    name: "Libema Open",
    slug: "libema-open",
    surface: "Gazon",
    country: "NL",
    city: "s-Hertogenbosch",
    category: "ATP 250",
  },
  {
    id: "tervuren-open",
    name: "Tennis Challenger DWC",
    slug: "tervuren-open",
    surface: "Dur",
    country: "BE",
    city: "Bruxelles",
    category: "ATP 250",
  },
  {
    id: "norrvingen-open",
    name: "Nordea Open",
    slug: "norrvingen-open",
    surface: "Terre",
    country: "SE",
    city: "Båstad",
    category: "ATP 250",
  },
  {
    id: "croatia-open-umag",
    name: "Croatia Open",
    slug: "croatia-open-umag",
    surface: "Terre",
    country: "HR",
    city: "Umag",
    category: "ATP 250",
  },
  {
    id: "ec-titlis-swiss-open",
    name: "EFG Swiss Open Gstaad",
    slug: "ec-titlis-swiss-open",
    surface: "Terre",
    country: "CH",
    city: "Gstaad",
    category: "ATP 250",
  },
  {
    id: " omv-ecotherm-open",
    name: "Generali Open",
    slug: " omv-ecotherm-open",
    surface: "Terre",
    country: "AT",
    city: "Kitzbühel",
    category: "ATP 250",
  },
  {
    id: "winston-salem-open",
    name: "Winston-Salem Open",
    slug: "winston-salem-open",
    surface: "Dur",
    country: "US",
    city: "Winston-Salem",
    category: "ATP 250",
  },
  {
    id: "moselle-open",
    name: "Moselle Open",
    slug: "moselle-open",
    surface: "Dur",
    country: "FR",
    city: "Metz",
    category: "ATP 250",
  },
  {
    id: "open-de-rouen-normandie",
    name: "Open de Rouen",
    slug: "open-de-rouen-normandie",
    surface: "Dur",
    country: "FR",
    city: "Rouen",
    category: "ATP 250",
  },
  {
    id: "almaty-open",
    name: "Almaty Open",
    slug: "almaty-open",
    surface: "Dur",
    country: "KZ",
    city: "Almaty",
    category: "ATP 250",
  },
  {
    id: "stockholm-open",
    name: "Stockholm Open",
    slug: "stockholm-open",
    surface: "Dur",
    country: "SE",
    city: "Stockholm",
    category: "ATP 250",
  },
  {
    id: "open-brest-cotedopale",
    name: "Brest Challenger",
    slug: "open-brest-cotedopale",
    surface: "Dur",
    country: "FR",
    city: "Brest",
    category: "Challenger",
  },
];

/**
 * Recherche fuzzy sur les tournois (sur nom + ville + pays).
 * Insensible à la casse et aux accents.
 */
export function searchTournaments(
  query: string,
  limit = 10,
): TournamentResult[] {
  const q = query
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
  if (q.length < 2) return [];
  return KNOWN_TOURNAMENTS.filter((t) => {
    const name = (t.name + " " + (t.city ?? "") + " " + (t.country ?? ""))
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
    return name.includes(q);
  }).slice(0, limit);
}
