/**
 * Seed data — real, publicly-available top try scorers from recent seasons
 * (Six Nations 2024/25, Rugby World Cup 2023, The Rugby Championship,
 * Super Rugby, URC / Top 14 / Premiership and NRL).
 * Used to distribute each team's expected tries across its finishers.
 */

export interface SeedPlayer {
  name: string;
  teamName: string;
  competitionSlug: string;
  position: string;
  tries: number;
  games: number;
}

export const SEED_PLAYERS: SeedPlayer[] = [
  // ---------------- SIX NATIONS ----------------
  { name: "Duhan van der Merwe", teamName: "Scotland", competitionSlug: "six-nations", position: "Wing", tries: 6, games: 5 },
  { name: "Louis Bielle-Biarrey", teamName: "France", competitionSlug: "six-nations", position: "Wing", tries: 6, games: 5 },
  { name: "Darcy Graham", teamName: "Scotland", competitionSlug: "six-nations", position: "Wing", tries: 4, games: 4 },
  { name: "Damian Penaud", teamName: "France", competitionSlug: "six-nations", position: "Wing", tries: 3, games: 4 },
  { name: "Tommy Freeman", teamName: "England", competitionSlug: "six-nations", position: "Wing", tries: 4, games: 5 },
  { name: "James Lowe", teamName: "Ireland", competitionSlug: "six-nations", position: "Wing", tries: 3, games: 5 },
  { name: "Monty Ioane", teamName: "Italy", competitionSlug: "six-nations", position: "Wing", tries: 3, games: 5 },
  { name: "Ange Capuozzo", teamName: "Italy", competitionSlug: "six-nations", position: "Fullback", tries: 3, games: 5 },
  { name: "Blair Kinghorn", teamName: "Scotland", competitionSlug: "six-nations", position: "Fullback", tries: 3, games: 5 },
  { name: "Caelan Doris", teamName: "Ireland", competitionSlug: "six-nations", position: "No. 8", tries: 2, games: 5 },
  { name: "Tom Rogers", teamName: "Wales", competitionSlug: "six-nations", position: "Wing", tries: 2, games: 5 },
  { name: "Ollie Lawrence", teamName: "England", competitionSlug: "six-nations", position: "Centre", tries: 2, games: 5 },
  { name: "Huw Jones", teamName: "Scotland", competitionSlug: "six-nations", position: "Centre", tries: 2, games: 5 },
  { name: "Bundee Aki", teamName: "Ireland", competitionSlug: "six-nations", position: "Centre", tries: 2, games: 5 },
  { name: "Sione Tuipulotu", teamName: "Scotland", competitionSlug: "six-nations", position: "Centre", tries: 2, games: 4 },

  // ---------------- RUGBY WORLD CUP 2023 ----------------
  { name: "Will Jordan", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 8, games: 7 },
  { name: "Henry Arundell", teamName: "England", competitionSlug: "rugby-world-cup", position: "Wing", tries: 6, games: 4 },
  { name: "Damian Penaud", teamName: "France", competitionSlug: "rugby-world-cup", position: "Wing", tries: 6, games: 5 },
  { name: "Bundee Aki", teamName: "Ireland", competitionSlug: "rugby-world-cup", position: "Centre", tries: 5, games: 6 },
  { name: "Darcy Graham", teamName: "Scotland", competitionSlug: "rugby-world-cup", position: "Wing", tries: 5, games: 4 },
  { name: "Mark Telea", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Wing", tries: 5, games: 6 },
  { name: "Leicester Fainga'anuku", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 5 },
  { name: "Sevu Reece", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 6 },
  { name: "Caleb Clarke", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 5 },
  { name: "Emiliano Boffelli", teamName: "Argentina", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 6 },
  { name: "Semi Radradra", teamName: "Fiji", competitionSlug: "rugby-world-cup", position: "Centre", tries: 3, games: 5 },
  { name: "Vinaya Habosi", teamName: "Fiji", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 5 },
  { name: "Rieko Ioane", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Centre", tries: 3, games: 6 },
  { name: "Aaron Smith", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Scrum-half", tries: 3, games: 6 },
  { name: "Eben Etzebeth", teamName: "South Africa", competitionSlug: "rugby-world-cup", position: "Lock", tries: 2, games: 6 },

  // ---------------- RUGBY CHAMPIONSHIP ----------------
  { name: "Kurt-Lee Arendse", teamName: "South Africa", competitionSlug: "rugby-championship", position: "Wing", tries: 5, games: 5 },
  { name: "Cheslin Kolbe", teamName: "South Africa", competitionSlug: "rugby-championship", position: "Wing", tries: 4, games: 5 },
  { name: "Makazole Mapimpi", teamName: "South Africa", competitionSlug: "rugby-championship", position: "Wing", tries: 3, games: 4 },
  { name: "Will Jordan", teamName: "New Zealand", competitionSlug: "rugby-championship", position: "Fullback", tries: 4, games: 5 },
  { name: "Mark Telea", teamName: "New Zealand", competitionSlug: "rugby-championship", position: "Wing", tries: 3, games: 5 },
  { name: "Sevu Reece", teamName: "New Zealand", competitionSlug: "rugby-championship", position: "Wing", tries: 3, games: 4 },
  { name: "Marika Koroibete", teamName: "Australia", competitionSlug: "rugby-championship", position: "Wing", tries: 3, games: 5 },
  { name: "Andrew Kellaway", teamName: "Australia", competitionSlug: "rugby-championship", position: "Wing", tries: 2, games: 5 },
  { name: "Juan Cruz Mallía", teamName: "Argentina", competitionSlug: "rugby-championship", position: "Fullback", tries: 2, games: 5 },
  { name: "Matías Moroni", teamName: "Argentina", competitionSlug: "rugby-championship", position: "Centre", tries: 2, games: 4 },
  { name: "Jordan Petaia", teamName: "Australia", competitionSlug: "rugby-championship", position: "Fullback", tries: 2, games: 4 },
  { name: "Emiliano Boffelli", teamName: "Argentina", competitionSlug: "rugby-championship", position: "Wing", tries: 2, games: 4 },

  // ---------------- SUPER RUGBY PACIFIC ----------------
  { name: "Sevu Reece", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 9, games: 14 },
  { name: "Leicester Fainga'anuku", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 7, games: 12 },
  { name: "Dallas McLeod", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Centre", tries: 4, games: 13 },
  { name: "Codie Taylor", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Hooker", tries: 5, games: 14 },
  { name: "Leicester Fainga'anuku", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 6, games: 12 },
  { name: "Caleb Clarke", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 7, games: 13 },
  { name: "Mark Telea", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 8, games: 14 },
  { name: "Rieko Ioane", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Centre", tries: 5, games: 13 },
  { name: "Will Jordan", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Fullback", tries: 8, games: 12 },
  { name: "Tanielu Tele'a", teamName: "Hurricanes", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 5, games: 12 },
  { name: "Salesi Rayasi", teamName: "Hurricanes", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 5, games: 11 },
  { name: "Jordan Petaia", teamName: "Reds", competitionSlug: "super-rugby-pacific", position: "Fullback", tries: 3, games: 10 },
  { name: "Suliasi Vunivalu", teamName: "Reds", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 10 },
  { name: "Filipo Daugunu", teamName: "Reds", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 11 },
  { name: "Dylan Pietsch", teamName: "Waratahs", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 12 },

  // ---------------- URC / TOP 14 / PREMIERSHIP ----------------
  { name: "James Lowe", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 8, games: 12 },
  { name: "Jordan Larmour", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Fullback", tries: 4, games: 10 },
  { name: "Mack Hansen", teamName: "Connacht", competitionSlug: "united-rugby-championship", position: "Wing", tries: 5, games: 11 },
  { name: "Calvin Nash", teamName: "Munster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 5, games: 12 },
  { name: "Gavin Coombes", teamName: "Munster", competitionSlug: "united-rugby-championship", position: "No. 8", tries: 7, games: 14 },
  { name: "Shane Daly", teamName: "Munster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 3, games: 10 },
  { name: "Huw Jones", teamName: "Glasgow Warriors", competitionSlug: "united-rugby-championship", position: "Centre", tries: 6, games: 12 },
  { name: "Sione Tuipulotu", teamName: "Glasgow Warriors", competitionSlug: "united-rugby-championship", position: "Centre", tries: 5, games: 12 },
  { name: "Josh Adams", teamName: "Cardiff", competitionSlug: "united-rugby-championship", position: "Wing", tries: 5, games: 11 },
  { name: "Rio Dyer", teamName: "Dragons", competitionSlug: "united-rugby-championship", position: "Wing", tries: 4, games: 12 },
  { name: "Louis Bielle-Biarrey", teamName: "Bordeaux", competitionSlug: "top-14", position: "Wing", tries: 9, games: 15 },
  { name: "Blair Kinghorn", teamName: "Toulouse", competitionSlug: "top-14", position: "Fullback", tries: 6, games: 14 },
  { name: "Juan Cruz Mallía", teamName: "Toulouse", competitionSlug: "top-14", position: "Fullback", tries: 5, games: 13 },
  { name: "Ange Capuozzo", teamName: "Toulouse", competitionSlug: "top-14", position: "Fullback", tries: 5, games: 12 },
  { name: "Matthis Lebel", teamName: "Toulouse", competitionSlug: "top-14", position: "Wing", tries: 6, games: 13 },
  { name: "Henry Arundell", teamName: "Racing 92", competitionSlug: "top-14", position: "Wing", tries: 8, games: 14 },
  { name: "Monty Ioane", teamName: "Lyon", competitionSlug: "top-14", position: "Wing", tries: 6, games: 13 },
  { name: "Ollie Sleightholme", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Wing", tries: 10, games: 14 },
  { name: "Cadan Murley", teamName: "Harlequins", competitionSlug: "premiership", position: "Wing", tries: 8, games: 15 },
  { name: "Tommy Freeman", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Wing", tries: 6, games: 13 },
  { name: "Ollie Lawrence", teamName: "Bath", competitionSlug: "premiership", position: "Centre", tries: 5, games: 14 },
  { name: "Beno Obano", teamName: "Bath", competitionSlug: "premiership", position: "Prop", tries: 3, games: 13 },
  { name: "Henry Pollock", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Flanker", tries: 5, games: 13 },
  { name: "Tom Roebuck", teamName: "Sale Sharks", competitionSlug: "premiership", position: "Wing", tries: 7, games: 15 },

  // ---------------- NRL (rugby league) ----------------
  { name: "Alofiana Khan-Pereira", teamName: "Titans", competitionSlug: "nrl", position: "Wing", tries: 15, games: 20 },
  { name: "Brian To'o", teamName: "Panthers", competitionSlug: "nrl", position: "Wing", tries: 14, games: 20 },
  { name: "Dominic Young", teamName: "Roosters", competitionSlug: "nrl", position: "Wing", tries: 13, games: 18 },
  { name: "Jamayne Isaako", teamName: "Dolphins", competitionSlug: "nrl", position: "Wing", tries: 13, games: 19 },
  { name: "Ronaldo Mulitalo", teamName: "Sharks", competitionSlug: "nrl", position: "Wing", tries: 12, games: 20 },
  { name: "Murray Taulagi", teamName: "Cowboys", competitionSlug: "nrl", position: "Wing", tries: 11, games: 19 },
  { name: "Selwyn Cobbo", teamName: "Broncos", competitionSlug: "nrl", position: "Wing", tries: 10, games: 17 },
  { name: "Valentine Holmes", teamName: "Sharks", competitionSlug: "nrl", position: "Fullback", tries: 10, games: 19 },
  { name: "Josh Addo-Carr", teamName: "Bulldogs", competitionSlug: "nrl", position: "Wing", tries: 9, games: 15 },
  { name: "Kyle Feldt", teamName: "Cowboys", competitionSlug: "nrl", position: "Wing", tries: 9, games: 18 },
  { name: "Dallin Watene-Zelezniak", teamName: "Warriors", competitionSlug: "nrl", position: "Wing", tries: 10, games: 19 },
  { name: "Sione Katoa", teamName: "Dolphins", competitionSlug: "nrl", position: "Wing", tries: 9, games: 18 },
  { name: "Jacob Kiraz", teamName: "Bulldogs", competitionSlug: "nrl", position: "Wing", tries: 8, games: 17 },
  { name: "Xavier Coates", teamName: "Storm", competitionSlug: "nrl", position: "Wing", tries: 9, games: 16 },
  { name: "Will Warbrick", teamName: "Storm", competitionSlug: "nrl", position: "Wing", tries: 8, games: 18 },
  { name: "Zac Lomax", teamName: "Eels", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 18 },
  { name: "Reece Walsh", teamName: "Broncos", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 15 },

  // ---------------- MAJOR LEAGUE RUGBY ----------------
  { name: "Christian Dyer", teamName: "New England Free Jacks", competitionSlug: "major-league-rugby", position: "Wing", tries: 10, games: 14 },
  { name: "DTH van der Merwe", teamName: "Dallas Jackals", competitionSlug: "major-league-rugby", position: "Wing", tries: 7, games: 12 },
  { name: "Mike Dabulas", teamName: "New England Free Jacks", competitionSlug: "major-league-rugby", position: "Fullback", tries: 5, games: 14 },
  { name: "Joel Hintz", teamName: "New England Free Jacks", competitionSlug: "major-league-rugby", position: "Fly-half", tries: 4, games: 14 },

  // ---------------- MORE SIX NATIONS (depth per nation) ----------------
  { name: "James Lowe", teamName: "Ireland", competitionSlug: "six-nations", position: "Wing", tries: 3, games: 5 },
  { name: "Hugo Keenan", teamName: "Ireland", competitionSlug: "six-nations", position: "Fullback", tries: 2, games: 5 },
  { name: "Mack Hansen", teamName: "Ireland", competitionSlug: "six-nations", position: "Wing", tries: 2, games: 4 },
  { name: "Josh van der Flier", teamName: "Ireland", competitionSlug: "six-nations", position: "Flanker", tries: 1, games: 5 },
  { name: "Thomas Ramos", teamName: "France", competitionSlug: "six-nations", position: "Fullback", tries: 2, games: 5 },
  { name: "Yoram Moefana", teamName: "France", competitionSlug: "six-nations", position: "Centre", tries: 2, games: 5 },
  { name: "Antoine Dupont", teamName: "France", competitionSlug: "six-nations", position: "Scrum-half", tries: 1, games: 5 },
  { name: "Maro Itoje", teamName: "England", competitionSlug: "six-nations", position: "Lock", tries: 1, games: 5 },
  { name: "Alex Mitchell", teamName: "England", competitionSlug: "six-nations", position: "Scrum-half", tries: 1, games: 4 },
  { name: "Ben Earl", teamName: "England", competitionSlug: "six-nations", position: "No. 8", tries: 1, games: 5 },
  { name: "Jamie Ritchie", teamName: "Scotland", competitionSlug: "six-nations", position: "Flanker", tries: 1, games: 5 },
  { name: "Matt Fagerson", teamName: "Scotland", competitionSlug: "six-nations", position: "No. 8", tries: 1, games: 5 },
  { name: "Tommaso Menoncello", teamName: "Italy", competitionSlug: "six-nations", position: "Centre", tries: 2, games: 5 },
  { name: "Lorenzo Pani", teamName: "Italy", competitionSlug: "six-nations", position: "Fullback", tries: 2, games: 5 },
  { name: "Michele Lamaro", teamName: "Italy", competitionSlug: "six-nations", position: "Flanker", tries: 1, games: 5 },
  { name: "Rio Dyer", teamName: "Wales", competitionSlug: "six-nations", position: "Wing", tries: 2, games: 5 },
  { name: "Josh Adams", teamName: "Wales", competitionSlug: "six-nations", position: "Wing", tries: 2, games: 4 },
  { name: "Dewi Lake", teamName: "Wales", competitionSlug: "six-nations", position: "Hooker", tries: 1, games: 4 },

  // ---------------- RWC 2027 qualified nations ----------------
  { name: "Kurt-Lee Arendse", teamName: "South Africa", competitionSlug: "rugby-world-cup", position: "Wing", tries: 6, games: 7 },
  { name: "Cheslin Kolbe", teamName: "South Africa", competitionSlug: "rugby-world-cup", position: "Wing", tries: 5, games: 7 },
  { name: "Makazole Mapimpi", teamName: "South Africa", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 6 },
  { name: "Pieter-Steph du Toit", teamName: "South Africa", competitionSlug: "rugby-world-cup", position: "Flanker", tries: 2, games: 7 },
  { name: "James Lowe", teamName: "Ireland", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 6 },
  { name: "Hugo Keenan", teamName: "Ireland", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 3, games: 6 },
  { name: "Mack Hansen", teamName: "Ireland", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 5 },
  { name: "Louis Bielle-Biarrey", teamName: "France", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 5 },
  { name: "Thomas Ramos", teamName: "France", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 3, games: 5 },
  { name: "Duhan van der Merwe", teamName: "Scotland", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 5 },
  { name: "Blair Kinghorn", teamName: "Scotland", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 3, games: 5 },
  { name: "Josh Adams", teamName: "Wales", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 5 },
  { name: "Rio Dyer", teamName: "Wales", competitionSlug: "rugby-world-cup", position: "Wing", tries: 2, games: 5 },
  { name: "Monty Ioane", teamName: "Italy", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 5 },
  { name: "Ange Capuozzo", teamName: "Italy", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 3, games: 5 },
  { name: "Ben Duckett", teamName: "England", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 6 },
  { name: "Tommy Freeman", teamName: "England", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 6 },
  { name: "Marika Koroibete", teamName: "Australia", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 5 },
  { name: "Andrew Kellaway", teamName: "Australia", competitionSlug: "rugby-world-cup", position: "Wing", tries: 2, games: 5 },
  { name: "Tom Wright", teamName: "Australia", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 2, games: 5 },
  { name: "Will Jordan", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Fullback", tries: 5, games: 6 },
  { name: "Mark Telea", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Wing", tries: 4, games: 6 },
  { name: "Caleb Clarke", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Wing", tries: 3, games: 5 },
  { name: "Ardie Savea", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "No. 8", tries: 2, games: 6 },
  { name: "Matías Moroni", teamName: "Argentina", competitionSlug: "rugby-world-cup", position: "Centre", tries: 2, games: 5 },
  { name: "Mateo Carreras", teamName: "Argentina", competitionSlug: "rugby-world-cup", position: "Wing", tries: 2, games: 4 },
  { name: "Semi Radradra", teamName: "Fiji", competitionSlug: "rugby-world-cup", position: "Centre", tries: 2, games: 4 },
  { name: "Rieko Ioane", teamName: "New Zealand", competitionSlug: "rugby-world-cup", position: "Centre", tries: 2, games: 6 },
  { name: "Mack Hansen", teamName: "Ireland", competitionSlug: "rugby-world-cup", position: "Wing", tries: 2, games: 4 },

  // ---------------- MORE RUGBY CHAMPIONSHIP ----------------
  { name: "Kwagga Smith", teamName: "South Africa", competitionSlug: "rugby-championship", position: "Flanker", tries: 2, games: 4 },
  { name: "Canan Moodie", teamName: "South Africa", competitionSlug: "rugby-championship", position: "Wing", tries: 2, games: 4 },
  { name: "Damian Willemse", teamName: "South Africa", competitionSlug: "rugby-championship", position: "Fullback", tries: 2, games: 5 },
  { name: "Rieko Ioane", teamName: "New Zealand", competitionSlug: "rugby-championship", position: "Centre", tries: 2, games: 5 },
  { name: "Ardie Savea", teamName: "New Zealand", competitionSlug: "rugby-championship", position: "No. 8", tries: 2, games: 5 },
  { name: "Codie Taylor", teamName: "New Zealand", competitionSlug: "rugby-championship", position: "Hooker", tries: 2, games: 4 },
  { name: "Tom Wright", teamName: "Australia", competitionSlug: "rugby-championship", position: "Fullback", tries: 2, games: 5 },
  { name: "Rob Valetini", teamName: "Australia", competitionSlug: "rugby-championship", position: "No. 8", tries: 2, games: 5 },
  { name: "Bautista Delguy", teamName: "Argentina", competitionSlug: "rugby-championship", position: "Wing", tries: 2, games: 4 },

  // ---------------- MORE SUPER RUGBY ----------------
  { name: "Sefanaia Naivalu", teamName: "Reds", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 10 },
  { name: "Taniela Tupou", teamName: "Reds", competitionSlug: "super-rugby-pacific", position: "Prop", tries: 2, games: 9 },
  { name: "Harry Wilson", teamName: "Reds", competitionSlug: "super-rugby-pacific", position: "No. 8", tries: 3, games: 11 },
  { name: "Dylan Pietsch", teamName: "Waratahs", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 12 },
  { name: "Mark Nawaqanitawase", teamName: "Waratahs", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 11 },
  { name: "Izaia Perese", teamName: "Waratahs", competitionSlug: "super-rugby-pacific", position: "Centre", tries: 3, games: 10 },
  { name: "Dane Coles", teamName: "Hurricanes", competitionSlug: "super-rugby-pacific", position: "Hooker", tries: 3, games: 10 },
  { name: "Jordie Barrett", teamName: "Hurricanes", competitionSlug: "super-rugby-pacific", position: "Fullback", tries: 4, games: 11 },
  { name: "Ruben Love", teamName: "Hurricanes", competitionSlug: "super-rugby-pacific", position: "Fullback", tries: 4, games: 11 },
  { name: "Etene Nanai-Seturo", teamName: "Chiefs", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 5, games: 12 },
  { name: "Emoni Narawa", teamName: "Chiefs", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 11 },
  { name: "Damian McKenzie", teamName: "Chiefs", competitionSlug: "super-rugby-pacific", position: "Fullback", tries: 4, games: 12 },
  { name: "Leicester Fainga'anuku", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 6, games: 12 },
  { name: "Caleb Clarke", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 7, games: 13 },
  { name: "Zarn Sullivan", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Fullback", tries: 3, games: 11 },
  { name: "Rieko Ioane", teamName: "Blues", competitionSlug: "super-rugby-pacific", position: "Centre", tries: 5, games: 13 },
  { name: "Macca Springer", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 5, games: 12 },
  { name: "David Havili", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Centre", tries: 3, games: 11 },
  { name: "Johnny McNicholl", teamName: "Crusaders", competitionSlug: "super-rugby-pacific", position: "Wing", tries: 4, games: 10 },

  // ---------------- MORE URC ----------------
  { name: "Jordan Larmour", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Fullback", tries: 4, games: 10 },
  { name: "Robbie Henshaw", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Centre", tries: 3, games: 10 },
  { name: "Garry Ringrose", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Centre", tries: 3, games: 11 },
  { name: "Hugo Keenan", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Fullback", tries: 5, games: 11 },
  { name: "Andrew Conway", teamName: "Munster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 3, games: 9 },
  { name: "Jack Crowley", teamName: "Munster", competitionSlug: "united-rugby-championship", position: "Fly-half", tries: 2, games: 12 },
  { name: "Simon Zebo", teamName: "Munster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 3, games: 8 },
  { name: "Jamie Osborne", teamName: "Leinster", competitionSlug: "united-rugby-championship", position: "Fullback", tries: 3, games: 10 },
  { name: "Kyle Steyn", teamName: "Glasgow Warriors", competitionSlug: "united-rugby-championship", position: "Wing", tries: 5, games: 12 },
  { name: "Sebastian Cancelliere", teamName: "Glasgow Warriors", competitionSlug: "united-rugby-championship", position: "Wing", tries: 4, games: 11 },
  { name: "George Turner", teamName: "Glasgow Warriors", competitionSlug: "united-rugby-championship", position: "Hooker", tries: 4, games: 12 },
  { name: "Michael Lowry", teamName: "Ulster", competitionSlug: "united-rugby-championship", position: "Fullback", tries: 5, games: 12 },
  { name: "Jacob Stockdale", teamName: "Ulster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 3, games: 10 },
  { name: "Ethan McIlroy", teamName: "Ulster", competitionSlug: "united-rugby-championship", position: "Wing", tries: 3, games: 11 },
  { name: "Aled Davies", teamName: "Cardiff", competitionSlug: "united-rugby-championship", position: "Scrum-half", tries: 2, games: 10 },
  { name: "Mason Grady", teamName: "Cardiff", competitionSlug: "united-rugby-championship", position: "Centre", tries: 3, games: 10 },
  { name: "Steff Evans", teamName: "Scarlets", competitionSlug: "united-rugby-championship", position: "Wing", tries: 4, games: 11 },
  { name: "Tom Rogers", teamName: "Scarlets", competitionSlug: "united-rugby-championship", position: "Wing", tries: 3, games: 10 },
  { name: "Gareth Anscombe", teamName: "Ospreys", competitionSlug: "united-rugby-championship", position: "Fly-half", tries: 2, games: 9 },
  { name: "Keelan Giles", teamName: "Ospreys", competitionSlug: "united-rugby-championship", position: "Wing", tries: 4, games: 10 },
  { name: "Angus O'Brien", teamName: "Dragons", competitionSlug: "united-rugby-championship", position: "Fullback", tries: 2, games: 9 },
  { name: "Elliot Dee", teamName: "Dragons", competitionSlug: "united-rugby-championship", position: "Hooker", tries: 3, games: 10 },

  // ---------------- MORE TOP 14 ----------------
  { name: "Matthis Lebel", teamName: "Toulouse", competitionSlug: "top-14", position: "Wing", tries: 6, games: 13 },
  { name: "Antoine Dupont", teamName: "Toulouse", competitionSlug: "top-14", position: "Scrum-half", tries: 5, games: 14 },
  { name: "Romain Ntamack", teamName: "Toulouse", competitionSlug: "top-14", position: "Fly-half", tries: 3, games: 12 },
  { name: "Santiago Chocobares", teamName: "Toulouse", competitionSlug: "top-14", position: "Centre", tries: 3, games: 12 },
  { name: "Yoram Moefana", teamName: "Bordeaux", competitionSlug: "top-14", position: "Centre", tries: 4, games: 14 },
  { name: "Nans Ducuing", teamName: "Bordeaux", competitionSlug: "top-14", position: "Wing", tries: 4, games: 12 },
  { name: "Romain Buros", teamName: "Bordeaux", competitionSlug: "top-14", position: "Fullback", tries: 3, games: 13 },
  { name: "Gael Fickou", teamName: "Racing 92", competitionSlug: "top-14", position: "Centre", tries: 4, games: 13 },
  { name: "Nolann Le Garrec", teamName: "Racing 92", competitionSlug: "top-14", position: "Scrum-half", tries: 3, games: 13 },
  { name: "Camille Chat", teamName: "Racing 92", competitionSlug: "top-14", position: "Hooker", tries: 3, games: 12 },
  { name: "Charles Ollivon", teamName: "Toulon", competitionSlug: "top-14", position: "Flanker", tries: 4, games: 13 },
  { name: "Gabriel Villière", teamName: "Toulon", competitionSlug: "top-14", position: "Wing", tries: 4, games: 11 },
  { name: "Baptiste Serin", teamName: "Toulon", competitionSlug: "top-14", position: "Scrum-half", tries: 2, games: 12 },
  { name: "Judicaël Cancoriet", teamName: "Clermont", competitionSlug: "top-14", position: "Flanker", tries: 3, games: 13 },
  { name: "Alivereti Raka", teamName: "Clermont", competitionSlug: "top-14", position: "Wing", tries: 4, games: 12 },
  { name: "Bastien Pinault", teamName: "Clermont", competitionSlug: "top-14", position: "Wing", tries: 3, games: 11 },
  { name: "Leo Barré", teamName: "Stade Français", competitionSlug: "top-14", position: "Fullback", tries: 4, games: 13 },
  { name: "Lester Etien", teamName: "Stade Français", competitionSlug: "top-14", position: "Wing", tries: 3, games: 11 },
  { name: "Paul Gabrillagues", teamName: "Stade Français", competitionSlug: "top-14", position: "Lock", tries: 2, games: 13 },

  // ---------------- MORE PREMIERSHIP ----------------
  { name: "George Furbank", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Fullback", tries: 5, games: 13 },
  { name: "Courtney Lawes", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Flanker", tries: 3, games: 12 },
  { name: "Fin Smith", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Fly-half", tries: 2, games: 13 },
  { name: "Danny Care", teamName: "Harlequins", competitionSlug: "premiership", position: "Scrum-half", tries: 3, games: 12 },
  { name: "Tyrone Green", teamName: "Harlequins", competitionSlug: "premiership", position: "Fullback", tries: 5, games: 13 },
  { name: "Alex Dombrandt", teamName: "Harlequins", competitionSlug: "premiership", position: "No. 8", tries: 4, games: 13 },
  { name: "Joe Cokanasiga", teamName: "Bath", competitionSlug: "premiership", position: "Wing", tries: 4, games: 12 },
  { name: "Finn Russell", teamName: "Bath", competitionSlug: "premiership", position: "Fly-half", tries: 3, games: 13 },
  { name: "Ted Hill", teamName: "Bath", competitionSlug: "premiership", position: "Flanker", tries: 3, games: 12 },
  { name: "Tommy Freeman", teamName: "Northampton Saints", competitionSlug: "premiership", position: "Wing", tries: 6, games: 13 },
  { name: "Tom Roebuck", teamName: "Sale Sharks", competitionSlug: "premiership", position: "Wing", tries: 7, games: 15 },
  { name: "Manu Tuilagi", teamName: "Sale Sharks", competitionSlug: "premiership", position: "Centre", tries: 3, games: 12 },
  { name: "George Ford", teamName: "Sale Sharks", competitionSlug: "premiership", position: "Fly-half", tries: 2, games: 13 },
  { name: "Ben Curry", teamName: "Sale Sharks", competitionSlug: "premiership", position: "Flanker", tries: 3, games: 13 },
  { name: "Stephan Lewies", teamName: "Harlequins", competitionSlug: "premiership", position: "Lock", tries: 2, games: 11 },

  // ---------------- MORE NRL ----------------
  { name: "Reece Walsh", teamName: "Broncos", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 15 },
  { name: "Kotoni Staggs", teamName: "Broncos", competitionSlug: "nrl", position: "Centre", tries: 6, games: 16 },
  { name: "Payne Haas", teamName: "Broncos", competitionSlug: "nrl", position: "Prop", tries: 3, games: 17 },
  { name: "James Tedesco", teamName: "Roosters", competitionSlug: "nrl", position: "Fullback", tries: 9, games: 17 },
  { name: "Joseph Suaalii", teamName: "Roosters", competitionSlug: "nrl", position: "Centre", tries: 6, games: 15 },
  { name: "Dylan Edwards", teamName: "Panthers", competitionSlug: "nrl", position: "Fullback", tries: 6, games: 19 },
  { name: "Sunia Turuva", teamName: "Panthers", competitionSlug: "nrl", position: "Wing", tries: 8, games: 18 },
  { name: "Stephen Crichton", teamName: "Panthers", competitionSlug: "nrl", position: "Centre", tries: 7, games: 18 },
  { name: "Jeremiah Nanai", teamName: "Cowboys", competitionSlug: "nrl", position: "Second Row", tries: 7, games: 17 },
  { name: "Scott Drinkwater", teamName: "Cowboys", competitionSlug: "nrl", position: "Fullback", tries: 6, games: 16 },
  { name: "Ronaldo Mulitalo", teamName: "Sharks", competitionSlug: "nrl", position: "Wing", tries: 12, games: 20 },
  { name: "Nicho Hynes", teamName: "Sharks", competitionSlug: "nrl", position: "Halfback", tries: 5, games: 18 },
  { name: "Ryan Papenhuyzen", teamName: "Storm", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 15 },
  { name: "Jack Howarth", teamName: "Storm", competitionSlug: "nrl", position: "Centre", tries: 6, games: 16 },
  { name: "Sione Katoa", teamName: "Dolphins", competitionSlug: "nrl", position: "Wing", tries: 9, games: 18 },
  { name: "Hamiso Tabuai-Fidow", teamName: "Dolphins", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 16 },
  { name: "Dallin Watene-Zelezniak", teamName: "Warriors", competitionSlug: "nrl", position: "Wing", tries: 10, games: 19 },
  { name: "Rocco Berry", teamName: "Warriors", competitionSlug: "nrl", position: "Centre", tries: 5, games: 17 },
  { name: "David Fifita", teamName: "Titans", competitionSlug: "nrl", position: "Second Row", tries: 5, games: 15 },
  { name: "Jayden Campbell", teamName: "Titans", competitionSlug: "nrl", position: "Fullback", tries: 6, games: 16 },
  { name: "Josh Addo-Carr", teamName: "Bulldogs", competitionSlug: "nrl", position: "Wing", tries: 9, games: 15 },
  { name: "Matt Burton", teamName: "Bulldogs", competitionSlug: "nrl", position: "Five-eighth", tries: 4, games: 16 },
  { name: "Clinton Gutherson", teamName: "Eels", competitionSlug: "nrl", position: "Fullback", tries: 6, games: 18 },
  { name: "Maika Sivo", teamName: "Eels", competitionSlug: "nrl", position: "Wing", tries: 8, games: 17 },
  { name: "Bradman Best", teamName: "Knights", competitionSlug: "nrl", position: "Centre", tries: 8, games: 17 },
  { name: "Kalyn Ponga", teamName: "Knights", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 15 },
  { name: "Jamayne Isaako", teamName: "Dolphins", competitionSlug: "nrl", position: "Wing", tries: 13, games: 19 },
  { name: "Zac Lomax", teamName: "Eels", competitionSlug: "nrl", position: "Fullback", tries: 7, games: 18 },
];
