'use strict';
/**
 * cs2Service.js — CS2 / CSGO data pipeline
 *
 * Primary : BSD CSGO addon  https://sports.bzzoiro.com/csgo/api/v2/
 * Rankings : data/hltv_rankings.json  (generated by tools/refresh_hltv_rankings.py)
 *
 * BSD status values: notstarted | inprogress | finished
 * BSD CS2 docs:      https://sports.bzzoiro.com/csgo/docs/
 */

const https = require('https');
const fs    = require('fs');
const path  = require('path');

// ─── Constants ───────────────────────────────────────────────────────────────
const ACTIVE_MAPS      = ['Mirage', 'Inferno', 'Nuke', 'Ancient', 'Anubis', 'Vertigo', 'Dust2'];
const CS2_BSD_TTL_MS   = 30 * 1000;       // 30 s live cache (BSD /live/ has 30s server cache)
const HLTV_FILE_TTL_MS = 60 * 60 * 1000;  // 1 h — re-read rankings JSON from disk
const CS2_BSD_BASE     = 'https://sports.bzzoiro.com/csgo';
const RANKINGS_FILE    = path.join(__dirname, '..', 'data', 'hltv_rankings.json');

// ─── Caches ──────────────────────────────────────────────────────────────────
let _cs2Cache        = { ts: 0, data: [] };
let _hltvRankCache   = { ts: 0, rankings: {} };    // teamName.lower() → { rank, points }
let _highlightsCache = { ts: 0, data: [] };        // ByMykel tournament highlights
let _stickersCache   = { ts: 0, byTeam: {} };      // teamName.lower() → best sticker img

// ─── ByMykel/CSGO-API constants ───────────────────────────────────────────────
const BYKEL_BASE           = 'https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en';
const BYKEL_HIGHLIGHTS_TTL = 60 * 60 * 1000;      // 1 h
const BYKEL_STICKERS_TTL   = 24 * 60 * 60 * 1000; // 24 h

// ─── Native https with timeout ───────────────────────────────────────────────
function _get(url, headers = {}, timeoutMs = 8000) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const options = {
      hostname : u.hostname,
      path     : u.pathname + u.search,
      method   : 'GET',
      headers  : { 'Accept': 'application/json', ...headers }
    };
    const req = https.request(options, res => {
      let body = '';
      res.on('data', c  => { body += c; });
      res.on('end',  () => {
        try { resolve({ status: res.statusCode, data: JSON.parse(body) }); }
        catch (_) { resolve({ status: res.statusCode, data: null }); }
      });
    });
    req.setTimeout(timeoutMs, () => { req.destroy(); reject(new Error('timeout')); });
    req.on('error', reject);
    req.end();
  });
}

// ─── BSD CS2 fetch with auth + retry ─────────────────────────────────────────
async function _bsdCs2(endpoint, apiKey, retries = 2) {
  const sep = endpoint.includes('?') ? '&' : '?';
  const url = `${CS2_BSD_BASE}${endpoint}${sep}tz=Europe/Paris`;
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const res = await _get(url, { 'Authorization': `Token ${apiKey}` });
      if (res.status === 200) return res;
      if (attempt < retries && (res.status >= 500 || res.status === 429)) {
        await new Promise(r => setTimeout(r, 1000 * (attempt + 1)));
        continue;
      }
      return res;
    } catch (e) {
      if (attempt < retries) { await new Promise(r => setTimeout(r, 1000 * (attempt + 1))); continue; }
      throw e;
    }
  }
}

// ─── HLTV rankings from local JSON (generated by tools/refresh_hltv_rankings.py) ───
function _loadHltvRankings() {
  if (Date.now() - _hltvRankCache.ts < HLTV_FILE_TTL_MS) return _hltvRankCache.rankings;
  try {
    if (!fs.existsSync(RANKINGS_FILE)) return {};
    const raw = JSON.parse(fs.readFileSync(RANKINGS_FILE, 'utf8'));
    const rankings = {};
    for (const t of (raw.teams || [])) {
      if (t.name) rankings[t.name.toLowerCase()] = { rank: t.rank, points: t.points || null };
    }
    _hltvRankCache = { ts: Date.now(), rankings };
    console.log(`[CS2/HLTV] Rankings loaded from file — ${Object.keys(rankings).length} teams`);
    return rankings;
  } catch (e) {
    console.warn('[CS2/HLTV] Could not load rankings file:', e.message);
    return {};
  }
}

// ─── Map advantage indicator ──────────────────────────────────────────────────
// t1MapStats / t2MapStats: { mirage: 72, inferno: 45, ... } (winrate %)
// Returns null when map unknown or no stats.
function computeMapAdvantage(t1MapStats, t2MapStats, currentMap) {
  if (!currentMap) return null;
  const key = currentMap.toLowerCase().replace(/[^a-z]/g, '');
  const t1wr = (t1MapStats || {})[key];
  const t2wr = (t2MapStats || {})[key];
  if (t1wr == null && t2wr == null) return null;
  const t1 = t1wr != null ? t1wr : 50;
  const t2 = t2wr != null ? t2wr : 50;
  const diff = t1 - t2;
  return {
    team1_wr  : t1,
    team2_wr  : t2,
    advantage : diff >= 20 ? 'team1' : diff <= -20 ? 'team2' : 'neutral',
    value_flag: Math.abs(diff) >= 20 ? '✓ Value Map' : null
  };
}

// ─── BSD image helper ─────────────────────────────────────────────────────────
// BSD CS2 image URL format: /img/csgo-team/{id}/?bg=transparent
function _teamLogo(teamId) {
  if (!teamId) return null;
  return `https://sports.bzzoiro.com/img/csgo-team/${teamId}/?bg=transparent`;
}
function _tournamentLogo(tournId) {
  if (!tournId) return null;
  return `https://sports.bzzoiro.com/img/csgo-tournament/${tournId}/?bg=transparent`;
}

// ─── Match normalization (BSD CS2 /api/v2/ schema) ───────────────────────────
function _normalizeMatch(raw, predictions) {
  // BSD CS2 status: notstarted | inprogress | finished
  const statusRaw = (raw.status || '').toLowerCase();
  const isLive    = statusRaw === 'inprogress';

  // Teams — BSD CS2 uses team1/team2 objects with id, name, logo fields
  const t1 = raw.team1 || raw.home_team || {};
  const t2 = raw.team2 || raw.away_team || {};

  // Scores: maps_score is series score, score is current map round score
  const maps1   = raw.team1_maps_won ?? raw.map_score_team1 ?? null;
  const maps2   = raw.team2_maps_won ?? raw.map_score_team2 ?? null;
  const rounds1 = raw.team1_score   ?? raw.score1 ?? null;
  const rounds2 = raw.team2_score   ?? raw.score2 ?? null;

  // Map info
  const currentMap = raw.current_map || raw.map_name || null;
  const mapNumber  = raw.map_number  || null;
  const bestOf     = raw.best_of     || raw.format || 3;

  // BSD CS2 logo: prefer image_url field, fallback to id-based URL
  const logo1 = raw.team1_logo || raw.team1?.image_url || _teamLogo(t1.id);
  const logo2 = raw.team2_logo || raw.team2?.image_url || _teamLogo(t2.id);
  const tourLogo = raw.tournament_logo || raw.tournament?.image_url || _tournamentLogo(raw.tournament?.id);

  // Prediction payload (if available from /predictions/ endpoint)
  const pred = predictions || null;

  return {
    id           : String(raw.id || `cs2_${Math.random().toString(36).slice(2)}`),
    sport        : 'cs2',
    tournament   : raw.tournament?.name || raw.tournament_name || raw.tournament || 'CS2',
    tournament_id: raw.tournament?.id   || null,
    tournament_logo: tourLogo,
    status       : isLive ? 'live' : statusRaw === 'finished' ? 'finished' : 'prematch',
    is_live      : isLive,
    scheduled    : raw.date || raw.scheduled || raw.start_time || null,
    best_of      : bestOf,
    current_map  : currentMap,
    map_number   : mapNumber,
    team1: {
      id        : t1.id   || null,
      name      : String(t1.name  || 'TBD'),
      logo      : logo1,
      country   : t1.country || null,
      hltv_rank : null   // enriched below
    },
    team2: {
      id        : t2.id   || null,
      name      : String(t2.name  || 'TBD'),
      logo      : logo2,
      country   : t2.country || null,
      hltv_rank : null
    },
    maps_score   : { team1: maps1,   team2: maps2   },
    round_score  : { team1: rounds1, team2: rounds2 },
    odds         : {
      team1: raw.odds_team1 ?? raw.team1_odds ?? raw.home_odds ?? null,
      team2: raw.odds_team2 ?? raw.team2_odds ?? raw.away_odds ?? null
    },
    prediction   : pred ? {
      team1_win_prob  : pred.home_win_prob   || null,
      team2_win_prob  : pred.away_win_prob   || null,
      predicted_winner: pred.predicted_winner || null,
      confidence      : pred.confidence      || null,
      team1_form      : pred.home_form_score || null,
      team2_form      : pred.away_form_score || null
    } : null,
    map_advantage: computeMapAdvantage(null, null, currentMap)
  };
}

// ─── Predictions fetch ────────────────────────────────────────────────────────
async function _fetchPredictions(apiKey) {
  try {
    const res = await _bsdCs2('/api/v2/predictions/', apiKey, 1);
    if (res && res.status === 200 && res.data) {
      const items = Array.isArray(res.data.results) ? res.data.results
                  : Array.isArray(res.data)          ? res.data
                  : [];
      // Index by match ID for fast lookup
      const byMatch = {};
      for (const p of items) {
        if (p.match) byMatch[String(p.match)] = p;
      }
      return byMatch;
    }
  } catch (_) { /* best-effort */ }
  return {};
}

// ─── ByMykel/CSGO-API fetcher ─────────────────────────────────────────────────
async function _byMykelFetch(file) {
  const res = await _get(`${BYKEL_BASE}/${file}`, {}, 10000);
  if (res.status !== 200 || !Array.isArray(res.data)) return [];
  return res.data;
}

// ─── Highlights (tournament match clips — video MP4 Steam CDN) ───────────────
async function fetchHighlights() {
  if (Date.now() - _highlightsCache.ts < BYKEL_HIGHLIGHTS_TTL) return _highlightsCache.data;
  try {
    const data = await _byMykelFetch('highlights.json');
    _highlightsCache = { ts: Date.now(), data };
    console.log(`[CS2/Highlights] ${data.length} clips loaded`);
    return data;
  } catch (e) {
    console.warn('[CS2/Highlights]', e.message);
    return _highlightsCache.data || [];
  }
}

// ─── Team stickers index (name.lower() → best sticker image URL) ─────────────
async function fetchTeamStickers() {
  if (Date.now() - _stickersCache.ts < BYKEL_STICKERS_TTL) return _stickersCache.byTeam;
  try {
    const raw = await _byMykelFetch('stickers.json');
    const byTeam = {};
    for (const s of raw) {
      // Name format: "Sticker | Team Vitality | Paris 2023" or "Sticker | Team Vitality (Holo) | Paris 2023"
      const parts = (s.name || '').split(' | ');
      if (parts.length < 2) continue;
      let teamName = parts[1].trim();
      // Strip variant suffix in parentheses: "FaZe Clan (Gold)" → "FaZe Clan"
      teamName = teamName.replace(/\s*\([^)]*\)\s*$/, '').trim();
      if (!teamName || teamName.length < 2) continue;
      const key = teamName.toLowerCase();
      // Keep first (most common) sticker per team, prefer non-foil
      if (!byTeam[key]) {
        byTeam[key] = { team: teamName, image: s.image, name: s.name };
      }
    }
    _stickersCache = { ts: Date.now(), byTeam };
    console.log(`[CS2/Stickers] ${Object.keys(byTeam).length} teams indexed`);
    return byTeam;
  } catch (e) {
    console.warn('[CS2/Stickers]', e.message);
    return _stickersCache.byTeam || {};
  }
}

// ─── Helper: find best sticker for a team name ───────────────────────────────
function findTeamSticker(teamName, stickersIndex) {
  if (!teamName || !stickersIndex) return null;
  const key = teamName.toLowerCase();
  if (stickersIndex[key]) return stickersIndex[key];
  // Fuzzy: check if any sticker key is contained in team name or vice versa
  for (const [k, v] of Object.entries(stickersIndex)) {
    if (key.includes(k) || k.includes(key)) return v;
  }
  return null;
}

// ─── Helper: find highlights for a match (by team names) ────────────────────
function findMatchHighlights(team1, team2, highlights, maxResults = 3) {
  if (!highlights || (!team1 && !team2)) return [];
  const n1 = (team1 || '').toLowerCase();
  const n2 = (team2 || '').toLowerCase();
  return highlights.filter(h => {
    const h0 = (h.team0 || '').toLowerCase();
    const h1 = (h.team1 || '').toLowerCase();
    const matchesT1 = n1 && (h0.includes(n1) || h1.includes(n1) || n1.includes(h0) || n1.includes(h1));
    const matchesT2 = n2 && (h0.includes(n2) || h1.includes(n2) || n2.includes(h0) || n2.includes(h1));
    return matchesT1 || matchesT2;
  }).slice(0, maxResults);
}

// ─── Public API ───────────────────────────────────────────────────────────────
module.exports = {
  ACTIVE_MAPS,
  computeMapAdvantage,
  fetchHighlights,
  fetchTeamStickers,
  findTeamSticker,
  findMatchHighlights,

  invalidateCache() { _cs2Cache.ts = 0; },

  async getCs2Matches(apiKey) {
    if (!apiKey) {
      console.warn('[CS2Service] BSD_API_KEY absent — CS2 feed disabled');
      return [];
    }
    if (Date.now() - _cs2Cache.ts < CS2_BSD_TTL_MS) return _cs2Cache.data;

    try {
      // Parallel: live matches + upcoming (notstarted) + predictions
      const [resLive, resUpcoming, predMap] = await Promise.all([
        _bsdCs2('/api/v2/matches/live/', apiKey).catch(() => null),
        _bsdCs2('/api/v2/matches/?status=notstarted&limit=100', apiKey).catch(() => null),
        _fetchPredictions(apiKey)
      ]);

      const raw = [];
      for (const res of [resLive, resUpcoming]) {
        if (!res || res.status !== 200 || !res.data) continue;
        const items = Array.isArray(res.data)          ? res.data
                    : Array.isArray(res.data.results)  ? res.data.results
                    : [];
        raw.push(...items);
      }

      // Fallback: generic list if both empty
      if (raw.length === 0) {
        const res = await _bsdCs2('/api/v2/matches/?limit=100', apiKey).catch(() => null);
        if (res && res.status === 200 && res.data) {
          const items = Array.isArray(res.data.results) ? res.data.results
                      : Array.isArray(res.data)         ? res.data
                      : [];
          raw.push(...items);
        }
      }

      // Normalize + attach predictions
      const matches = raw.map(m => _normalizeMatch(m, predMap[String(m.id)] || null));

      // Attach HLTV rankings from local JSON file (no HTTP call)
      const hltvR = _loadHltvRankings();
      for (const m of matches) {
        const r1 = hltvR[m.team1.name.toLowerCase()];
        const r2 = hltvR[m.team2.name.toLowerCase()];
        m.team1.hltv_rank = r1 ? r1.rank : null;
        m.team2.hltv_rank = r2 ? r2.rank : null;
      }

      // Sort: live first → then by date
      matches.sort((a, b) => {
        if (a.is_live !== b.is_live) return a.is_live ? -1 : 1;
        if (a.scheduled && b.scheduled) return new Date(a.scheduled) - new Date(b.scheduled);
        return 0;
      });

      _cs2Cache = { ts: Date.now(), data: matches };
      console.log(`[CS2Service] ${matches.length} matches (${matches.filter(m => m.is_live).length} live, ${Object.keys(predMap).length} predictions)`);
      return matches;

    } catch (e) {
      console.warn('[CS2Service] Fetch error:', e.message);
      return _cs2Cache.data || [];
    }
  }
};
