'use strict';
/**
 * cs2Service.js — CS2 / CSGO data pipeline
 *
 * Primary : BSD CSGO addon  https://sports.bzzoiro.com/csgo/api/v2/
 * Rankings : data/hltv_rankings.json  (generated by tools/refresh_hltv_rankings.py)
 *
 * BSD status values: notstarted | inprogress | finished
 * BSD CS2 docs:      https://sports.bzzoiro.com/csgo/docs/
 */

const https = require('https');
const fs    = require('fs');
const path  = require('path');

// ─── Constants ───────────────────────────────────────────────────────────────
const ACTIVE_MAPS      = ['Mirage', 'Inferno', 'Nuke', 'Ancient', 'Anubis', 'Vertigo', 'Dust2'];

// Source→source canonicalisation: BSD & HLTV may use slightly different team names.
// Keys = lowercase canonical HLTV name; values = array of recognised alternate strings.
const TEAM_ALIASES = {
  'vitality':       ['team vitality', 'vitality', 'vita'],
  'faze':           ['faze clan', 'faze', 'fazeclan'],
  'spirit':         ['team spirit', 'spirit', 'spirit team'],
  'mouz':           ['mouz', 'mousesports'],
  'natus vincere':  ['natus vincere', 'navi', 'nat. vincere'],
  'g2':             ['g2 esports', 'g2', 'g2esports'],
  'liquid':         ['team liquid', 'liquid'],
  'heroic':         ['heroic'],
  'furia':          ['furia esports', 'furia'],
  'complexity':     ['complexity gaming', 'complexity', 'col'],
  'cloud9':         ['cloud9', 'c9'],
  'astralis':       ['astralis'],
  'big':            ['big', 'big clan'],
  'pain':           ['pain gaming', 'pain', 'paingaming'],
  'ence':           ['ence'],
  'falcons':        ['team falcons', 'falcons'],
  'virtus.pro':     ['virtus.pro', 'virtus pro', 'vp'],
  'ninjas in pyjamas': ['ninjas in pyjamas', 'nip', 'n.i.p.'],
  'fnatic':         ['fnatic'],
  'mongolz':        ['the mongolz', 'mongolz', 'mongol z'],
  '3dmax':          ['3dmax'],
  'monte':          ['monte'],
  'saw':            ['saw'],
  'eternos':        ['eternos'],
  'sinners':        ['sinners esports', 'sinners'],
  'imperial':       ['imperial esports', 'imperial', 'imp'],
  'aurora':         ['aurora gaming', 'aurora'],
  '9z':             ['9z team', '9z'],
  'apeks':          ['apeks'],
  'lynn vision':    ['lynn vision', 'lynn']
};

function _normalizeTeamName(raw) {
  if (!raw) return raw;
  const s = raw.toLowerCase().trim();
  for (const [canon, aliases] of Object.entries(TEAM_ALIASES)) {
    if (s === canon || aliases.includes(s)) return canon;
  }
  return s;
}

const CS2_BSD_TTL_MS   = 30 * 1000;       // 30 s live cache (BSD /live/ has 30s server cache)
const HLTV_FILE_TTL_MS = 60 * 60 * 1000;  // 1 h — re-read rankings JSON from disk
const CS2_BSD_BASE     = 'https://sports.bzzoiro.com/csgo';
const RANKINGS_FILE    = path.join(__dirname, '..', 'data', 'hltv_rankings.json');

// ─── Caches ──────────────────────────────────────────────────────────────────
let _cs2Cache        = { ts: 0, data: [] };
let _cs2Fetching     = false;
let _hltvRankCache   = { ts: 0, rankings: {} };    // teamName.lower() → { rank, points }
let _highlightsCache = { ts: 0, data: [] };        // ByMykel tournament highlights
let _stickersCache   = { ts: 0, byTeam: {} };      // teamName.lower() → best sticker img

// ─── ByMykel/CSGO-API constants ───────────────────────────────────────────────
const BYKEL_BASE           = 'https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en';
const BYKEL_HIGHLIGHTS_TTL = 60 * 60 * 1000;      // 1 h
const BYKEL_STICKERS_TTL   = 24 * 60 * 60 * 1000; // 24 h

// ─── Native https with timeout ───────────────────────────────────────────────
function _get(url, headers = {}, timeoutMs = 8000) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const options = {
      hostname : u.hostname,
      path     : u.pathname + u.search,
      method   : 'GET',
      headers  : { 'Accept': 'application/json', ...headers }
    };
    const req = https.request(options, res => {
      let body = '';
      res.on('data', c  => { body += c; });
      res.on('end',  () => {
        try { resolve({ status: res.statusCode, data: JSON.parse(body) }); }
        catch (_) { resolve({ status: res.statusCode, data: null }); }
      });
    });
    req.setTimeout(timeoutMs, () => { req.destroy(); reject(new Error('timeout')); });
    req.on('error', reject);
    req.end();
  });
}

// ─── BSD CS2 fetch with auth + retry ─────────────────────────────────────────
async function _bsdCs2(endpoint, apiKey, retries = 2) {
  const sep = endpoint.includes('?') ? '&' : '?';
  const url = `${CS2_BSD_BASE}${endpoint}${sep}tz=Europe/Paris`;
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const res = await _get(url, { 'Authorization': `Token ${apiKey}` });
      if (res.status === 200) return res;
      if (attempt < retries && (res.status >= 500 || res.status === 429)) {
        await new Promise(r => setTimeout(r, 1000 * (attempt + 1)));
        continue;
      }
      return res;
    } catch (e) {
      if (attempt < retries) { await new Promise(r => setTimeout(r, 1000 * (attempt + 1))); continue; }
      throw e;
    }
  }
}

// ─── HLTV rankings from local JSON (generated by tools/refresh_hltv_rankings.py) ───
function _loadHltvRankings() {
  if (Date.now() - _hltvRankCache.ts < HLTV_FILE_TTL_MS) return _hltvRankCache.rankings;
  try {
    if (!fs.existsSync(RANKINGS_FILE)) return {};
    const raw = JSON.parse(fs.readFileSync(RANKINGS_FILE, 'utf8'));
    const rankings = {};
    for (const t of (raw.teams || [])) {
      if (t.name) rankings[t.name.toLowerCase()] = { rank: t.rank, points: t.points || null };
    }
    _hltvRankCache = { ts: Date.now(), rankings };
    console.log(`[CS2/HLTV] Rankings loaded from file — ${Object.keys(rankings).length} teams`);
    return rankings;
  } catch (e) {
    console.warn('[CS2/HLTV] Could not load rankings file:', e.message);
    return {};
  }
}

// ─── BSD CS2 team bulk fetch (ELO + map_stats) ───────────────────────────────
let _bsdTeamsBulkCache = { ts: 0, byName: {}, byId: {} };
const BSD_TEAMS_BULK_TTL = 6 * 60 * 60 * 1000; // 6h
let _bsdTeamDetailCache = new Map(); // id → { ts, data }
const BSD_TEAM_DETAIL_TTL = 24 * 60 * 60 * 1000; // 24h
let _bsdApiKeyRef = null; // stored on first call

async function fetchBSDCs2Teams(apiKey) {
  _bsdApiKeyRef = apiKey || _bsdApiKeyRef;
  if (!_bsdApiKeyRef) return {};
  if (Date.now() - _bsdTeamsBulkCache.ts < BSD_TEAMS_BULK_TTL) return _bsdTeamsBulkCache.byName;
  try {
    // BSD paginates at 50/page — follow full next URLs directly (avoid _bsdCs2 base-prefix doubling)
    const byName = {}, byId = {};
    const authHdr = { 'Authorization': `Token ${_bsdApiKeyRef}`, 'Accept': 'application/json' };
    let url = `${CS2_BSD_BASE}/api/v2/teams/?page_size=100&tz=Europe/Paris`;
    let pages = 0;
    while (url && pages < 20) { // safety cap: 20 pages × ~50 = 1000 teams max
      const res = await _get(url, authHdr, 10000);
      if (!res || res.status !== 200) break;
      const items = Array.isArray(res.data?.results) ? res.data.results
                  : Array.isArray(res.data)           ? res.data
                  : [];
      for (const t of items) {
        if (!t.name) continue;
        const entry = { id: t.id, elo_rating: t.elo_rating || null, elo_peak: t.elo_peak || null };
        byName[t.name.toLowerCase()] = entry;
        const normName = _normalizeTeamName(t.name);
        if (normName) byName[normName] = entry;
        if (t.short_name) byName[t.short_name.toLowerCase()] = entry;
        if (t.id) byId[t.id] = entry;
      }
      // next is already a full URL — use directly, no base-prefix manipulation
      url = res.data?.next || null;
      pages++;
    }
    _bsdTeamsBulkCache = { ts: Date.now(), byName, byId };
    console.log(`[CS2/BSD-Teams] ${Object.keys(byId).length} teams with ELO loaded (${pages} pages)`);
    return byName;
  } catch (e) { console.warn('[CS2/BSD-Teams]', e.message); return _bsdTeamsBulkCache.byName; }
}

async function fetchBSDCs2TeamDetail(teamId) {
  if (!teamId || !_bsdApiKeyRef) return null;
  const cid = String(teamId);
  const cached = _bsdTeamDetailCache.get(cid);
  if (cached && Date.now() - cached.ts < BSD_TEAM_DETAIL_TTL) return cached.data;
  try {
    const res = await _bsdCs2(`/api/v2/teams/${cid}/`, _bsdApiKeyRef, 1);
    if (!res || res.status !== 200 || !res.data) return null;
    _bsdTeamDetailCache.set(cid, { ts: Date.now(), data: res.data });
    return res.data;
  } catch (e) { return null; }
}

// ─── BSD CS2 veto/map-picks fetch ────────────────────────────────────────────
let _vetoCache = new Map(); // matchId → { ts, data }
const VETO_TTL_MS = 20 * 1000; // 20s — veto changes frequently pre-match

async function fetchMatchVeto(matchId, apiKey) {
  const _key = String(matchId);
  const _key2 = apiKey || _bsdApiKeyRef;
  if (!_key2) return null;
  const cached = _vetoCache.get(_key);
  if (cached && Date.now() - cached.ts < VETO_TTL_MS) return cached.data;
  try {
    const res = await _bsdCs2(`/api/v2/matches/${_key}/`, _key2, 1);
    if (!res || res.status !== 200 || !res.data) return null;
    const veto = res.data.map_picks || res.data.veto || res.data.map_veto || null;
    _vetoCache.set(_key, { ts: Date.now(), data: veto });
    return veto;
  } catch (e) { return null; }
}

// Convert BSD team map_stats → HLTV-compatible lookup { mapNameLower: winrate% }
// Also preserves CT/T side winrates as _round_winrate_ct/_t fields.
function _bsdMapStatsToLookup(bsdMapStats) {
  if (!bsdMapStats || !Array.isArray(bsdMapStats.maps)) return null;
  const out = {
    _map_winrate: bsdMapStats.map_winrate ?? null,
    _round_winrate_t: bsdMapStats.round_winrate_t ?? null,
    _round_winrate_ct: bsdMapStats.round_winrate_ct ?? null,
    _sample_size: bsdMapStats.sample_size ?? null,
  };
  for (const m of bsdMapStats.maps) {
    if (m.map) out[m.map.toLowerCase()] = m.winrate;
  }
  return out;
}

// ─── Map advantage indicator ──────────────────────────────────────────────────
// t1MapStats / t2MapStats: { mirage: 72, inferno: 45, ... } (winrate %)
// Returns null when map unknown or no stats.
function computeMapAdvantage(t1MapStats, t2MapStats, currentMap) {
  if (!currentMap) return null;
  const key = currentMap.toLowerCase().replace(/[^a-z]/g, '');
  const t1wr = (t1MapStats || {})[key];
  const t2wr = (t2MapStats || {})[key];
  if (t1wr == null && t2wr == null) return null;
  const t1 = t1wr != null ? t1wr : 50;
  const t2 = t2wr != null ? t2wr : 50;
  const diff = t1 - t2;
  const winner = diff >= 20 ? 'team1' : diff <= -20 ? 'team2' : 'neutral';
  return {
    team1_wr       : t1,
    team2_wr       : t2,
    advantage      : winner,
    value_flag     : Math.abs(diff) >= 20 ? '✓ Value Map' : null,
    recommended_bet: Math.abs(diff) >= 20
      ? `${diff > 0 ? 'T1' : 'T2'} sur ${currentMap} (écart ${Math.abs(diff)}pp · wr ${Math.max(t1, t2)}%)`
      : null
  };
}

// ─── BSD image helper ─────────────────────────────────────────────────────────
// BSD CS2 image URL format: /img/csgo-team/{id}/?bg=transparent
function _teamLogo(teamId) {
  if (!teamId) return null;
  return `https://sports.bzzoiro.com/img/csgo-team/${teamId}/?bg=transparent`;
}
function _tournamentLogo(tournId) {
  if (!tournId) return null;
  return `https://sports.bzzoiro.com/img/csgo-tournament/${tournId}/?bg=transparent`;
}

// ─── Match normalization (BSD CS2 /api/v2/ schema) ───────────────────────────
function _normalizeMatch(raw, predictions, mapStats) {
  // BSD CS2 status: notstarted | inprogress | finished
  const statusRaw = (raw.status || '').toLowerCase();
  const isLive    = statusRaw === 'inprogress';

  // Teams — BSD CS2 uses team1/team2 objects with id, name, logo fields
  const t1 = raw.team1 || raw.home_team || {};
  const t2 = raw.team2 || raw.away_team || {};
  const lookup = mapStats || {};

  // Scores: maps_score is series score, score is current map round score
  const maps1   = raw.team1_maps_won ?? raw.map_score_team1 ?? null;
  const maps2   = raw.team2_maps_won ?? raw.map_score_team2 ?? null;
  const rounds1 = raw.team1_score   ?? raw.score1 ?? null;
  const rounds2 = raw.team2_score   ?? raw.score2 ?? null;

  // Map info
  const currentMap = raw.current_map || raw.map_name || null;
  const mapNumber  = raw.map_number  || null;
  const bestOf     = raw.best_of     || raw.format || 3;

  // BSD CS2 logo: prefer image_url field, fallback to id-based URL
  const logo1 = raw.team1_logo || raw.team1?.image_url || _teamLogo(t1.id);
  const logo2 = raw.team2_logo || raw.team2?.image_url || _teamLogo(t2.id);
  const tourLogo = raw.tournament_logo || raw.tournament?.image_url || _tournamentLogo(raw.tournament?.id);

  // Prediction payload (if available from /predictions/ endpoint)
  const pred = predictions || null;

  return {
    id           : String(raw.id || `cs2_${Math.random().toString(36).slice(2)}`),
    sport        : 'cs2',
    tournament   : raw.tournament?.name || raw.tournament_name || raw.tournament || 'CS2',
    tournament_id: raw.tournament?.id   || null,
    tournament_logo: tourLogo,
    status       : isLive ? 'live' : statusRaw === 'finished' ? 'finished' : 'prematch',
    is_live      : isLive,
    scheduled    : raw.date || raw.scheduled || raw.start_time || null,
    best_of      : bestOf,
    current_map  : currentMap,
    map_number   : mapNumber,
    team1: {
      id        : t1.id   || null,
      name      : _normalizeTeamName(t1.name) || 'TBD',
      logo      : logo1,
      country   : t1.country || null,
      hltv_rank : null   // enriched below
    },
    team2: {
      id        : t2.id   || null,
      name      : _normalizeTeamName(t2.name) || 'TBD',
      logo      : logo2,
      country   : t2.country || null,
      hltv_rank : null
    },
    maps_score   : { team1: maps1,   team2: maps2   },
    round_score  : { team1: rounds1, team2: rounds2 },
    odds         : {
      team1: raw.odds_team1 ?? raw.team1_odds ?? raw.home_odds ?? null,
      team2: raw.odds_team2 ?? raw.team2_odds ?? raw.away_odds ?? null
    },
    prediction   : pred ? {
      team1_win_prob  : pred.home_win_prob   || null,
      team2_win_prob  : pred.away_win_prob   || null,
      predicted_winner: pred.predicted_winner || null,
      confidence      : pred.confidence      || null,
      team1_form      : pred.home_form_score || null,
      team2_form      : pred.away_form_score || null
    } : null,
    is_lan      : /IEM|ESL|PGL|BLAST|Major|EPL|Pro League|ELEAGUE|ESWC|DreamHack/i.test(
                    raw.tournament?.name || raw.tournament_name || String(raw.tournament || '')),
    map_advantage: computeMapAdvantage(
      lookup[_normalizeTeamName(t1.name)?.toLowerCase()],
      lookup[_normalizeTeamName(t2.name)?.toLowerCase()],
      currentMap
    )
  };
}

// ─── Predictions fetch ────────────────────────────────────────────────────────
async function _fetchPredictions(apiKey) {
  try {
    const res = await _bsdCs2('/api/v2/predictions/', apiKey, 1);
    if (res && res.status === 200 && res.data) {
      const items = Array.isArray(res.data.results) ? res.data.results
                  : Array.isArray(res.data)          ? res.data
                  : [];
      // Index by match ID for fast lookup
      const byMatch = {};
      for (const p of items) {
        if (p.match) byMatch[String(p.match)] = p;
      }
      return byMatch;
    }
  } catch (_) { /* best-effort */ }
  return {};
}

// ─── ByMykel/CSGO-API fetcher ─────────────────────────────────────────────────
async function _byMykelFetch(file) {
  const res = await _get(`${BYKEL_BASE}/${file}`, {}, 10000);
  if (res.status !== 200 || !Array.isArray(res.data)) return [];
  return res.data;
}

// ─── Highlights (tournament match clips — video MP4 Steam CDN) ───────────────
async function fetchHighlights() {
  if (Date.now() - _highlightsCache.ts < BYKEL_HIGHLIGHTS_TTL) return _highlightsCache.data;
  try {
    const data = await _byMykelFetch('highlights.json');
    _highlightsCache = { ts: Date.now(), data };
    console.log(`[CS2/Highlights] ${data.length} clips loaded`);
    return data;
  } catch (e) {
    console.warn('[CS2/Highlights]', e.message);
    return _highlightsCache.data || [];
  }
}

// ─── Team stickers index (name.lower() → best sticker image URL) ─────────────
async function fetchTeamStickers() {
  if (Date.now() - _stickersCache.ts < BYKEL_STICKERS_TTL) return _stickersCache.byTeam;
  try {
    const raw = await _byMykelFetch('stickers.json');
    const byTeam = {};
    for (const s of raw) {
      // Name format: "Sticker | Team Vitality | Paris 2023" or "Sticker | Team Vitality (Holo) | Paris 2023"
      const parts = (s.name || '').split(' | ');
      if (parts.length < 2) continue;
      let teamName = parts[1].trim();
      // Strip variant suffix in parentheses: "FaZe Clan (Gold)" → "FaZe Clan"
      teamName = teamName.replace(/\s*\([^)]*\)\s*$/, '').trim();
      if (!teamName || teamName.length < 2) continue;
      const key = teamName.toLowerCase();
      // Keep first (most common) sticker per team, prefer non-foil
      if (!byTeam[key]) {
        byTeam[key] = { team: teamName, image: s.image, name: s.name };
      }
    }
    _stickersCache = { ts: Date.now(), byTeam };
    console.log(`[CS2/Stickers] ${Object.keys(byTeam).length} teams indexed`);
    return byTeam;
  } catch (e) {
    console.warn('[CS2/Stickers]', e.message);
    return _stickersCache.byTeam || {};
  }
}

// ─── Helper: find best sticker for a team name ───────────────────────────────
function findTeamSticker(teamName, stickersIndex) {
  if (!teamName || !stickersIndex) return null;
  const key = teamName.toLowerCase();
  if (stickersIndex[key]) return stickersIndex[key];
  // Fuzzy: check if any sticker key is contained in team name or vice versa
  for (const [k, v] of Object.entries(stickersIndex)) {
    if (key.includes(k) || k.includes(key)) return v;
  }
  return null;
}

// ─── Helper: find highlights for a match (by team names) ────────────────────
function findMatchHighlights(team1, team2, highlights, maxResults = 3) {
  if (!highlights || (!team1 && !team2)) return [];
  const n1 = (team1 || '').toLowerCase();
  const n2 = (team2 || '').toLowerCase();
  return highlights.filter(h => {
    const h0 = (h.team0 || '').toLowerCase();
    const h1 = (h.team1 || '').toLowerCase();
    const matchesT1 = n1 && (h0.includes(n1) || h1.includes(n1) || n1.includes(h0) || n1.includes(h1));
    const matchesT2 = n2 && (h0.includes(n2) || h1.includes(n2) || n2.includes(h0) || n2.includes(h1));
    return matchesT1 || matchesT2;
  }).slice(0, maxResults);
}

// ═══════════════════════════════════════════════════════════════════════════════
// OVER ROUNDS MODEL — csapi.de (free, no auth)
// Stratégie : avg total rounds par équipe × map × last 90j × rank_tier adversaire
// Source     : https://api.csapi.de
// Données    : matches[].maps[].{team1_score, team2_score} + team.rank
// ═══════════════════════════════════════════════════════════════════════════════

const CSAPI_BASE          = 'https://api.csapi.de';
const CSAPI_MATCHES_TTL   = 6 * 60 * 60 * 1000;  // 6 h — updated daily, no need to hammer
const CSAPI_RANKINGS_TTL  = 6 * 60 * 60 * 1000;  // 6 h
const OVER_MODEL_DAYS     = 90;                   // fenêtre historique

let _csapiMatchesCache  = { ts: 0, data: [] };
let _csapiRankingsCache = { ts: 0, byName: {} }; // teamName.lower() → { rank, points }
let _mapIndexCache      = { ts: 0, index: {} };   // teamName.lower() → mapKey → { rounds[], opp_ranks[], n }

// ─── csapi.de fetch helper ────────────────────────────────────────────────────
async function _csapiGet(path, timeoutMs = 10000) {
  const res = await _get(`${CSAPI_BASE}${path}`, { 'Accept': 'application/json' }, timeoutMs);
  return res;
}

// ─── Fetch match history (csapi.de /matches/latest) ──────────────────────────
async function fetchCsApiMatches() {
  if (Date.now() - _csapiMatchesCache.ts < CSAPI_MATCHES_TTL) return _csapiMatchesCache.data;
  try {
    // Try with days param first, fallback to plain endpoint
    let res = await _csapiGet('/matches/latest?days=90').catch(() => null);
    if (!res || res.status !== 200) {
      res = await _csapiGet('/matches/latest').catch(() => null);
    }
    if (res && res.status === 200 && res.data) {
      // Handle both direct array and wrapped formats: { matches:[...] } / { data:[...] } / [...]
      const arr = Array.isArray(res.data) ? res.data
                : Array.isArray(res.data.matches) ? res.data.matches
                : Array.isArray(res.data.data)    ? res.data.data
                : Array.isArray(res.data.results) ? res.data.results
                : [];
      _csapiMatchesCache = { ts: Date.now(), data: arr };
      console.log(`[CS2/OverModel] ${arr.length} matches fetched from csapi.de`);
      return arr;
    }
  } catch (e) { console.warn('[CS2/OverModel] Match fetch:', e.message); }
  return _csapiMatchesCache.data || [];
}

// ─── Fetch current rankings (csapi.de /rankings) ─────────────────────────────
async function fetchCsApiRankings() {
  if (Date.now() - _csapiRankingsCache.ts < CSAPI_RANKINGS_TTL) return _csapiRankingsCache.byName;
  try {
    const res = await _csapiGet('/rankings/').catch(() => null);
    if (res && res.status === 200 && res.data) {
      const arr = Array.isArray(res.data) ? res.data : (res.data.rankings || []);
      const byName = {};
      for (const t of arr) {
        if (t.name) byName[t.name.toLowerCase()] = { id: t.id || null, rank: t.rank, points: t.points };
      }
      _csapiRankingsCache = { ts: Date.now(), byName };
      console.log(`[CS2/OverModel] ${Object.keys(byName).length} teams in rankings`);
      return byName;
    }
  } catch (e) { console.warn('[CS2/OverModel] Rankings fetch:', e.message); }
  return _csapiRankingsCache.byName || {};
}

// ─── Build per-team per-map rounds index ─────────────────────────────────────
function _buildMapIndex(matches, lastDays = OVER_MODEL_DAYS) {
  const cutoff = Date.now() - lastDays * 24 * 3600 * 1000;
  const index  = {};

  for (const match of matches) {
    const matchTs = new Date(match.date || 0).getTime();
    if (matchTs < cutoff) continue;
    if (!match.maps || !match.team1 || !match.team2) continue;

    const t1key  = (match.team1.name || '').toLowerCase();
    const t2key  = (match.team2.name || '').toLowerCase();
    const t1rank = Number(match.team1.rank) || null;
    const t2rank = Number(match.team2.rank) || null;

    for (const map of match.maps) {
      if (!map.name) continue;
      const s1 = Number(map.team1_score);
      const s2 = Number(map.team2_score);
      if (!Number.isFinite(s1) || !Number.isFinite(s2)) continue;
      const total = s1 + s2;
      if (total < 13 || total > 45) continue; // sanity check

      const mapKey = map.name.toLowerCase().replace(/[^a-z]/g, '');

      const _add = (teamKey, oppRank) => {
        if (!index[teamKey]) index[teamKey] = {};
        if (!index[teamKey][mapKey]) index[teamKey][mapKey] = { rounds: [], opp_ranks: [], n: 0, avg: 0, std: 0 };
        index[teamKey][mapKey].rounds.push(total);
        index[teamKey][mapKey].opp_ranks.push(oppRank);
        index[teamKey][mapKey].n++;
      };

      _add(t1key, t2rank);
      _add(t2key, t1rank);
    }
  }

  // Compute avg + std per team-map
  for (const maps of Object.values(index)) {
    for (const stat of Object.values(maps)) {
      if (!stat.rounds.length) continue;
      stat.avg = stat.rounds.reduce((a, b) => a + b, 0) / stat.rounds.length;
      const variance = stat.rounds.reduce((s, r) => s + (r - stat.avg) ** 2, 0) / stat.rounds.length;
      stat.std = Math.sqrt(variance);
    }
  }

  return index;
}

// ─── Rank-filtered avg (fallback to global if not enough filtered data) ───────
function _filteredAvg(stat, oppRank, rankWindow = 15) {
  if (!stat || !stat.rounds.length) return null;
  if (oppRank == null) return { avg: stat.avg, n: stat.n };
  const filt = stat.rounds.filter((_, i) => {
    const opp = stat.opp_ranks[i];
    return opp == null || Math.abs(opp - oppRank) <= rankWindow;
  });
  if (filt.length < 3) return { avg: stat.avg, n: stat.n }; // not enough → use all
  const avg = filt.reduce((a, b) => a + b, 0) / filt.length;
  return { avg, n: filt.length };
}

// ─── Public: compute Over Rounds model for a match ───────────────────────────
// Returns null if no data. Signal: { OVER | UNDER } against closest standard line.
async function computeMapOverModel(t1name, t2name, mapName, oppRankWindow = 15) {
  if (!mapName || !t1name || !t2name) return null;

  // Refresh index if stale
  if (Date.now() - _mapIndexCache.ts > CSAPI_MATCHES_TTL) {
    const matches = await fetchCsApiMatches();
    _mapIndexCache = { ts: Date.now(), index: _buildMapIndex(matches) };
  }
  const idx = _mapIndexCache.index;

  // Current rankings for rank-tier filtering
  const rankings = await fetchCsApiRankings();
  const t1rank = (rankings[t1name.toLowerCase()] || {}).rank || null;
  const t2rank = (rankings[t2name.toLowerCase()] || {}).rank || null;

  const mapKey = mapName.toLowerCase().replace(/[^a-z]/g, '');
  const t1stat = (idx[t1name.toLowerCase()] || {})[mapKey] || null;
  const t2stat = (idx[t2name.toLowerCase()] || {})[mapKey] || null;

  const t1res = _filteredAvg(t1stat, t2rank, oppRankWindow);
  const t2res = _filteredAvg(t2stat, t1rank, oppRankWindow);

  if (!t1res && !t2res) return null;

  const avg1 = t1res ? t1res.avg : null;
  const avg2 = t2res ? t2res.avg : null;

  let predicted;
  if (avg1 != null && avg2 != null) predicted = (avg1 + avg2) / 2;
  else predicted = avg1 ?? avg2;

  // Standard bookmaker CS2 round lines
  const LINES = [24.5, 25.5, 26.5, 27.5, 28.5];
  const bestLine = LINES.reduce((p, c) => Math.abs(c - predicted) < Math.abs(p - predicted) ? c : p);
  const signal   = predicted > bestLine ? 'OVER' : 'UNDER';
  const nTotal   = (t1res?.n || 0) + (t2res?.n || 0);
  const confidence = nTotal >= 20 ? 'HIGH' : nTotal >= 8 ? 'MED' : 'LOW';

  return {
    map         : mapName,
    team1       : { name: t1name, avg: avg1 != null ? +avg1.toFixed(1) : null, n: t1res?.n || 0, rank: t1rank },
    team2       : { name: t2name, avg: avg2 != null ? +avg2.toFixed(1) : null, n: t2res?.n || 0, rank: t2rank },
    predicted   : +predicted.toFixed(1),
    line        : bestLine,
    signal,
    confidence,
    n_total     : nTotal,
    window_days : OVER_MODEL_DAYS,
    rank_window : oppRankWindow
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// ENRICHMENT LAYER — Form · H2H · Player Stats · Streak · HLTV Map Winrates
// ═══════════════════════════════════════════════════════════════════════════════

const CSAPI_TEAM_TTL      = 6 * 60 * 60 * 1000;   // 6h
const CSAPI_PLAYERS_TTL   = 6 * 60 * 60 * 1000;   // 6h
const HLTV_MAPSTATS_FILE  = path.join(__dirname, '..', 'data', 'hltv_team_mapstats.json');
const HLTV_MAPSTATS_TTL   = 24 * 60 * 60 * 1000;  // 24h re-read from disk

let _csapiTeamCache    = {};   // teamId → { ts, data }
let _csapiPlayersCache = { ts: 0, byName: {}, byTeam: {} };  // byName: playerName.lower() → stats | byTeam: teamName.lower() → [stats]
let _hltvMapStatsCache = { ts: 0, byTeam: {} };  // teamName.lower() → { Mirage: 72, Inferno: 48, ... }

// ─── csapi.de: player stats index ────────────────────────────────────────────
async function fetchCsApiPlayerStats() {
  if (Date.now() - _csapiPlayersCache.ts < CSAPI_PLAYERS_TTL) return _csapiPlayersCache.byName;
  try {
    const res = await _csapiGet('/players/stats').catch(() => null);
    if (res && res.status === 200 && Array.isArray(res.data)) {
      const byName = {}, byTeam = {};
      for (const p of res.data) {
        if (!p.name) continue;
        const kd   = p.d > 0 ? +(p.k / p.d).toFixed(2) : null;
        const entry = {
          id: p.id, name: p.name, rank: p.rank,
          rating: p.rating || null, adr: p.adr || null,
          kast: p.kast || null, kd, kills: p.k, deaths: p.d,
          swing: p.swing || null, maps: p.N || null,
          team: p.team || null,
        };
        byName[p.name.toLowerCase()] = entry;
        // Build team→players index (csapi.de includes team name per player)
        if (p.team) {
          const tk = _normalizeTeamName(p.team) || p.team.toLowerCase();
          if (!byTeam[tk]) byTeam[tk] = [];
          byTeam[tk].push(entry);
          // Also index by raw team name lower for fallback
          const rawTk = p.team.toLowerCase();
          if (rawTk !== tk) { if (!byTeam[rawTk]) byTeam[rawTk] = []; byTeam[rawTk].push(entry); }
        }
      }
      // Sort each team's players by rating desc
      for (const tk of Object.keys(byTeam)) byTeam[tk].sort((a, b) => (b.rating || 0) - (a.rating || 0));
      _csapiPlayersCache = { ts: Date.now(), byName, byTeam };
      console.log(`[CS2/Players] ${Object.keys(byName).length} players | ${Object.keys(byTeam).length} teams indexed`);
      return byName;
    }
  } catch (e) { console.warn('[CS2/Players]', e.message); }
  return _csapiPlayersCache.byName || {};
}

// Returns players array for a team by name (from byTeam index built in fetchCsApiPlayerStats)
function getPlayersByTeamName(teamName) {
  const tk  = _normalizeTeamName(teamName) || (teamName || '').toLowerCase();
  const raw = (teamName || '').toLowerCase();
  return _csapiPlayersCache.byTeam[tk]
      || _csapiPlayersCache.byTeam[raw]
      || [];
}

// ─── csapi.de: team info (streak + roster) ───────────────────────────────────
async function fetchCsApiTeamInfo(teamId) {
  const cached = _csapiTeamCache[teamId];
  if (cached && Date.now() - cached.ts < CSAPI_TEAM_TTL) return cached.data;
  try {
    const res = await _csapiGet(`/teams/${teamId}`).catch(() => null);
    if (res && res.status === 200 && res.data) {
      _csapiTeamCache[teamId] = { ts: Date.now(), data: res.data };
      return res.data;
    }
  } catch (_) {}
  return null;
}

// ─── Derive team form from match history (last N matches W/L) ────────────────
// ─── BO1 exclusion filter (not representative of major tournament performance) ─
function _isBO1(m) {
  const bo = m.best_of || m.format || m.type;
  if (!bo) return false;
  if (typeof bo === 'number') return bo === 1;
  const s = String(bo).toLowerCase().replace(/[^a-z0-9]/g,'');
  return s === 'bo1' || s === '1';
}

function buildTeamForm(teamName, matches, n = 10) {
  const key = teamName.toLowerCase();
  // Handle both {name:string} and plain string for team1/team2
  function _tname(t) { return (typeof t === 'string' ? t : (t?.name || '')).toLowerCase(); }

  const relevant = matches
    .filter(m => {
      if (_isBO1(m)) return false;
      const t1 = _tname(m.team1); const t2 = _tname(m.team2);
      return t1 === key || t2 === key || _normalizeTeamName(t1) === key || _normalizeTeamName(t2) === key;
    })
    .sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0))
    .slice(0, n);

  if (!relevant.length) return null;

  const form = relevant.map(m => {
    const winner = _tname(m.winner);
    const normW  = _normalizeTeamName(winner);
    if (!winner) return 'N';
    if (winner === key || normW === key) return 'W';
    return 'L';
  }).reverse(); // chronological order (oldest→newest)

  const wins = form.filter(r => r === 'W').length;
  const played = form.filter(r => r !== 'N').length;
  return {
    form,
    wins,
    losses : form.filter(r => r === 'L').length,
    winrate: played > 0 ? Math.round((wins / played) * 100) : null,
    n      : relevant.length
  };
}

// ─── Derive H2H from match history ───────────────────────────────────────────
function buildH2H(t1name, t2name, matches, n = 20) {
  const k1 = t1name.toLowerCase();
  const k2 = t2name.toLowerCase();
  const h2h = matches.filter(m => {
    if (_isBO1(m)) return false;
    function _tn(t) { return (typeof t === 'string' ? t : (t?.name || '')).toLowerCase(); }
    const mt1 = _tn(m.team1); const mt2 = _tn(m.team2);
    const nmt1 = _normalizeTeamName(mt1); const nmt2 = _normalizeTeamName(mt2);
    return (mt1 === k1 || nmt1 === k1) && (mt2 === k2 || nmt2 === k2)
        || (mt1 === k2 || nmt1 === k2) && (mt2 === k1 || nmt2 === k1);
  }).sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0)).slice(0, n);

  if (!h2h.length) return null;

  let t1wins = 0, t2wins = 0;
  const results = h2h.map(m => {
    function _tn2(t) { return (typeof t === 'string' ? t : (t?.name || '')).toLowerCase(); }
    const winner = _tn2(m.winner); const normW = _normalizeTeamName(winner);
    if (winner === k1 || normW === k1) { t1wins++; return 'T1'; }
    if (winner === k2 || normW === k2) { t2wins++; return 'T2'; }
    return 'N';
  }).reverse();

  return { t1wins, t2wins, results, n: h2h.length, last_date: h2h[0]?.date || null };
}

// ─── HLTV map winrates from local JSON (generated by tools/refresh_hltv_team_mapstats.js) ─
function loadHltvMapStats() {
  if (Date.now() - _hltvMapStatsCache.ts < HLTV_MAPSTATS_TTL) return _hltvMapStatsCache.byTeam;
  try {
    if (!fs.existsSync(HLTV_MAPSTATS_FILE)) return {};
    const raw = JSON.parse(fs.readFileSync(HLTV_MAPSTATS_FILE, 'utf8'));
    const byTeam = {};
    for (const t of (raw.teams || [])) {
      if (t.name) byTeam[t.name.toLowerCase()] = t.maps || {};
    }
    _hltvMapStatsCache = { ts: Date.now(), byTeam };
    console.log(`[CS2/MapStats] HLTV map winrates: ${Object.keys(byTeam).length} teams`);
    return byTeam;
  } catch (e) { console.warn('[CS2/MapStats]', e.message); return {}; }
}

// ─── Get roster player stats for a team ──────────────────────────────────────
async function getTeamPlayerStats(roster, playerIndex) {
  if (!roster || !playerIndex) return [];
  return roster
    .map(p => playerIndex[(p.name || '').toLowerCase()] || null)
    .filter(Boolean)
    .sort((a, b) => (b.rating || 0) - (a.rating || 0))
    .slice(0, 5);
}

// ─── Form Score SOS-weighted (0-100, opponent strength adjusted) ─────────────
// Weights wins against top-ranked opponents higher than wins vs lower-ranked.
// Returns null if no data. Falls back to BSD prediction form_score if provided.
function computeFormScore(teamName, matches) {
  const key = teamName.toLowerCase();
  function _tn(t) { return (typeof t === 'string' ? t : (t?.name || '')).toLowerCase(); }
  const relevant = matches
    .filter(m => {
      if (_isBO1(m)) return false;
      const mt1 = _tn(m.team1); const mt2 = _tn(m.team2);
      return mt1 === key || mt2 === key || _normalizeTeamName(mt1) === key || _normalizeTeamName(mt2) === key;
    })
    .sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0))
    .slice(0, 15);
  if (!relevant.length) return null;
  let sumW = 0, sumR = 0;
  for (const m of relevant) {
    const isT1 = _tn(m.team1) === key || _normalizeTeamName(_tn(m.team1)) === key;
    const oppRankRaw = isT1 ? (m.team2?.rank ?? 50) : (m.team1?.rank ?? 50);
    const oppRank    = typeof oppRankRaw === 'number' ? oppRankRaw : 50;
    const weight     = 1 + Math.max(0, 50 - oppRank) / 50; // top-50 opp → up to 2x weight
    const winnerN    = _tn(m.winner);
    const won        = (winnerN === key || _normalizeTeamName(winnerN) === key) ? 1 : 0;
    sumW += weight; sumR += won * weight;
  }
  return Math.round((sumR / sumW) * 100);
}

// ─── Form Score → trajectory proxy (when csapi.de match history unavailable) ──
function _formScoreToTraj(score) {
  if (score == null) return null;
  if (score >= 70) return { arrow: '↗',  label: 'RISING',    last3: [], wins_last3: null, n: 0, source: 'form_score' };
  if (score >= 50) return { arrow: '→',  label: 'STABLE',    last3: [], wins_last3: null, n: 0, source: 'form_score' };
  if (score >= 35) return { arrow: '↘',  label: 'DECLINING', last3: [], wins_last3: null, n: 0, source: 'form_score' };
  return              { arrow: '↓↓', label: 'COLD',      last3: [], wins_last3: null, n: 0, source: 'form_score' };
}

// ─── Roster Strength Score (normalized mean Rating, 0-100) ───────────────────
// Star bonus: +5pts per player rating >1.30 (capped 0-100)
function computeRosterStrength(players) {
  if (!players || !players.length) return null;
  const ratings = players.map(p => p.rating || 1.0).filter(r => r > 0);
  if (!ratings.length) return null;
  const mean = ratings.reduce((a, b) => a + b, 0) / ratings.length;
  const stars = ratings.filter(r => r > 1.30).length;
  const base  = Math.max(0, Math.min(1, (mean - 0.70) / 0.80)); // [0.70, 1.50] → [0,1]
  return Math.round(Math.min(1, base + stars * 0.05) * 100);
}

// ─── Map Pool Entropy (Shannon, normalized 0-100) ─────────────────────────────
// Low (<70) = concentrated pool = vulnerable to veto forcing
function computeMapPoolEntropy(mapStats) {
  if (!mapStats || typeof mapStats !== 'object') return null;
  const wrs = Object.entries(mapStats)
    .filter(([k]) => !k.startsWith('_'))
    .map(([, v]) => typeof v === 'number' ? v : null)
    .filter(v => v != null);
  if (wrs.length < 3) return null;
  const total = wrs.reduce((a, b) => a + b, 0);
  if (!total) return null;
  const probs = wrs.map(w => w / total);
  const H    = -probs.reduce((s, p) => s + (p > 0 ? p * Math.log2(p) : 0), 0);
  const maxH = Math.log2(wrs.length);
  const norm = maxH > 0 ? H / maxH : 1;
  return {
    entropy      : Math.round(H * 100) / 100,
    normalized   : Math.round(norm * 100),       // 0=concentrated, 100=uniform
    maps_n       : wrs.length,
    concentrated : norm < 0.70,                  // flag: pool vulnerable to veto
  };
}

// ─── Form Trajectory (last-2+ results → arrow + label) ───────────────────────
// Threshold 2 (not 3) — csapi.de coverage often sparse for top teams
function computeFormTrajectory(form) {
  if (!form || !form.form || form.form.length < 2) return null;
  const last3 = form.form.slice(-3); // up to 3, minimum 2
  const wins  = last3.filter(r => r === 'W').length;
  const n     = last3.length;
  let arrow, label;
  if (wins === n)           { arrow = '↑↑'; label = 'HOT'; }
  else if (wins >= n * 0.6) { arrow = '↗';  label = 'RISING'; }
  else if (wins >= n * 0.4) { arrow = '→';  label = 'STABLE'; }
  else if (wins > 0)        { arrow = '↘';  label = 'DECLINING'; }
  else                      { arrow = '↓↓'; label = 'COLD'; }
  return { arrow, label, last3, wins_last3: wins, n };
}

// ─── Pistol Index — CT/T round winrate differential as pistol proxy ───────────
// BSD map_stats.round_winrate_ct / _t correlates strongly with pistol outcomes
function computePistolIndex(t1meta, t2meta) {
  const t1ct = t1meta?.round_winrate_ct ?? null;
  const t1t  = t1meta?.round_winrate_t  ?? null;
  const t2ct = t2meta?.round_winrate_ct ?? null;
  const t2t  = t2meta?.round_winrate_t  ?? null;
  if (t1ct == null && t1t == null && t2ct == null && t2t == null) return null;
  const dCT = (t1ct ?? 50) - (t2ct ?? 50);
  const dT  = (t1t  ?? 50) - (t2t  ?? 50);
  const sigCT = Math.abs(dCT) >= 10 ? (dCT > 0 ? 'T1' : 'T2') : 'neutral';
  const sigT  = Math.abs(dT)  >= 10 ? (dT  > 0 ? 'T1' : 'T2') : 'neutral';
  const parts = [];
  if (sigCT !== 'neutral') parts.push(sigCT + ' CT');
  if (sigT  !== 'neutral') parts.push(sigT  + ' T');
  return {
    ct_delta    : Math.round(dCT * 10) / 10,
    t_delta     : Math.round(dT  * 10) / 10,
    signal_ct   : sigCT,
    signal_t    : sigT,
    t1_ct_wr    : t1ct, t1_t_wr: t1t,
    t2_ct_wr    : t2ct, t2_t_wr: t2t,
    trade_signal: parts.length ? parts.join(' | ') + ' pistol edge' : null,
  };
}

// ─── Master enrichment: all stats for a matchup ──────────────────────────────
async function buildMatchEnrichment(t1name, t2name, mapName, apiKey) {
  const [matches, rankings, playerStats] = await Promise.all([
    fetchCsApiMatches().catch(() => []),
    fetchCsApiRankings().catch(() => ({})),
    fetchCsApiPlayerStats().catch(() => ({}))
  ]);

  const t1form       = buildTeamForm(t1name, matches, 10);
  const t2form       = buildTeamForm(t2name, matches, 10);
  const t1form_score = computeFormScore(t1name, matches);
  const t2form_score = computeFormScore(t2name, matches);
  const h2h    = buildH2H(t1name, t2name, matches, 15);
  const mapStats = loadHltvMapStats();

  // BSD team detail: ELO + map_stats (CT/T winrate) — parallel fetch
  const bsdTeams = await fetchBSDCs2Teams(apiKey).catch(() => ({}));
  const b1entry = bsdTeams[t1name.toLowerCase()];
  const b2entry = bsdTeams[t2name.toLowerCase()];
  const [bsdT1Detail, bsdT2Detail] = await Promise.allSettled([
    b1entry?.id ? fetchBSDCs2TeamDetail(b1entry.id) : Promise.resolve(null),
    b2entry?.id ? fetchBSDCs2TeamDetail(b2entry.id) : Promise.resolve(null),
  ]);
  const bsdT1 = bsdT1Detail.status === 'fulfilled' ? bsdT1Detail.value : null;
  const bsdT2 = bsdT2Detail.status === 'fulfilled' ? bsdT2Detail.value : null;
  const bsdMaps1 = bsdT1?.map_stats ? _bsdMapStatsToLookup(bsdT1.map_stats) : null;
  const bsdMaps2 = bsdT2?.map_stats ? _bsdMapStatsToLookup(bsdT2.map_stats) : null;

  // Team IDs for streak lookup
  const t1rank = rankings[t1name.toLowerCase()];
  const t2rank = rankings[t2name.toLowerCase()];
  const [t1info, t2info] = await Promise.allSettled([
    t1rank ? fetchCsApiTeamInfo(t1rank.id || null) : Promise.resolve(null),
    t2rank ? fetchCsApiTeamInfo(t2rank.id || null) : Promise.resolve(null)
  ]);
  const t1data = t1info.status === 'fulfilled' ? t1info.value : null;
  const t2data = t2info.status === 'fulfilled' ? t2info.value : null;

  // Player stats: byTeam direct lookup (primary) → roster fallback (secondary)
  const t1byTeam = getPlayersByTeamName(t1name);
  const t2byTeam = getPlayersByTeamName(t2name);
  const t1players = t1byTeam.length ? t1byTeam.slice(0, 5) : await getTeamPlayerStats(t1data?.roster, playerStats);
  const t2players = t2byTeam.length ? t2byTeam.slice(0, 5) : await getTeamPlayerStats(t2data?.roster, playerStats);

  // HLTV map winrates for current map
  const mapKey = (mapName || '').toLowerCase().replace('de_', '');
  // BSD map_stats primary, HLTV file fallback
  const t1maps = bsdMaps1 || mapStats[t1name.toLowerCase()] || {};
  const t2maps = bsdMaps2 || mapStats[t2name.toLowerCase()] || {};
  const mapSource = bsdMaps1 ? 'bsd' : Object.keys(mapStats[t1name.toLowerCase()] || {}).length > 0 ? 'hltv' : 'unavailable';

  const mapWinrate = mapName ? {
    map    : mapName,
    team1  : t1maps[mapKey] ?? null,
    team2  : t2maps[mapKey] ?? null,
    source : mapSource,
    // BSD CT/T side advantage on this map (new edge signal)
    team1_ct_wr: bsdMaps1?._round_winrate_ct ?? null,
    team1_t_wr : bsdMaps1?._round_winrate_t  ?? null,
    team2_ct_wr: bsdMaps2?._round_winrate_ct ?? null,
    team2_t_wr : bsdMaps2?._round_winrate_t  ?? null,
  } : null;

  // ─── Derived analytics (new P0 metrics) ─────────────────────────────────────
  const t1meta = bsdMaps1 ? { round_winrate_ct: bsdMaps1._round_winrate_ct, round_winrate_t: bsdMaps1._round_winrate_t } : null;
  const t2meta = bsdMaps2 ? { round_winrate_ct: bsdMaps2._round_winrate_ct, round_winrate_t: bsdMaps2._round_winrate_t } : null;
  const t1mapsClean = Object.fromEntries(Object.entries(t1maps).filter(([k]) => !k.startsWith('_')));
  const t2mapsClean = Object.fromEntries(Object.entries(t2maps).filter(([k]) => !k.startsWith('_')));

  return {
    team1: {
      name           : t1name,
      rank           : t1rank?.rank || null,
      elo_rating     : b1entry?.elo_rating ?? null,
      elo_peak       : b1entry?.elo_peak   ?? null,
      streak         : t1data?.streak ?? null,
      form           : t1form,
      form_score     : t1form_score,
      form_trajectory: computeFormTrajectory(t1form) || _formScoreToTraj(t1form_score),
      players        : t1players,
      roster_strength: computeRosterStrength(t1players),
      map_pool_entropy: computeMapPoolEntropy(t1mapsClean),
      all_maps       : Object.keys(t1mapsClean).length > 0 ? t1mapsClean : null,
      map_stats_meta : bsdMaps1 ? {
        map_winrate: bsdMaps1._map_winrate, round_winrate_ct: bsdMaps1._round_winrate_ct,
        round_winrate_t: bsdMaps1._round_winrate_t, sample_size: bsdMaps1._sample_size,
      } : null,
    },
    team2: {
      name           : t2name,
      rank           : t2rank?.rank || null,
      elo_rating     : b2entry?.elo_rating ?? null,
      elo_peak       : b2entry?.elo_peak   ?? null,
      streak         : t2data?.streak ?? null,
      form           : t2form,
      form_score     : t2form_score,
      form_trajectory: computeFormTrajectory(t2form) || _formScoreToTraj(t2form_score),
      players        : t2players,
      roster_strength: computeRosterStrength(t2players),
      map_pool_entropy: computeMapPoolEntropy(t2mapsClean),
      all_maps       : Object.keys(t2mapsClean).length > 0 ? t2mapsClean : null,
      map_stats_meta : bsdMaps2 ? {
        map_winrate: bsdMaps2._map_winrate, round_winrate_ct: bsdMaps2._round_winrate_ct,
        round_winrate_t: bsdMaps2._round_winrate_t, sample_size: bsdMaps2._sample_size,
      } : null,
    },
    h2h,
    map_winrate : mapWinrate,
    pistol_index: computePistolIndex(t1meta, t2meta),
    data_age_h  : Math.round((Date.now() - _csapiMatchesCache.ts) / 3600000)
  };
}

// ─── Live Momentum Ring Buffer ────────────────────────────────────────────────
const MOMENTUM_RING   = 5;
const _roundHistories = new Map(); // matchId → { ring, t1, t2 }

function _updateRoundHistory(matchId, rounds1, rounds2) {
  if (rounds1 == null || rounds2 == null) return;
  const key  = String(matchId);
  const prev = _roundHistories.get(key) || { ring: [], t1: null, t2: null };
  if (rounds1 === prev.t1 && rounds2 === prev.t2) return;
  const ring = prev.ring.slice();
  const d1 = rounds1 - (prev.t1 != null ? prev.t1 : rounds1);
  const d2 = rounds2 - (prev.t2 != null ? prev.t2 : rounds2);
  for (let i = 0; i < Math.max(0, d1); i++) { ring.push(1);  if (ring.length > MOMENTUM_RING) ring.shift(); }
  for (let i = 0; i < Math.max(0, d2); i++) { ring.push(-1); if (ring.length > MOMENTUM_RING) ring.shift(); }
  _roundHistories.set(key, { ring, t1: rounds1, t2: rounds2 });
}

function computeLiveMomentum(matchId, rounds1, rounds2) {
  _updateRoundHistory(matchId, rounds1, rounds2);
  const hist = _roundHistories.get(String(matchId));
  const ring = hist ? hist.ring : [];
  // Weighted recent rounds (most recent = highest weight)
  const W = [0.10, 0.15, 0.20, 0.25, 0.30];
  let mom = 0;
  for (let i = 0; i < ring.length; i++) {
    mom += ring[i] * (W[ring.length - 1 - i] || 0.2) * 100;
  }
  mom = Math.round(Math.max(-100, Math.min(100, mom)));
  // Infer eco state: consecutive losses in current half
  function _ecoState(won, total) {
    const halfLen = Math.min(total, 12); // CS2 MR12: first half 12 rounds max
    const losses  = halfLen - Math.min(won, halfLen);
    if (losses >= 3) return 'eco';
    if (losses >= 2) return 'semi-eco';
    return 'full-buy';
  }
  const total   = (rounds1 || 0) + (rounds2 || 0);
  const streak3 = ring.slice(-3);
  const streak  = streak3.length >= 3 && streak3.every(v => v === streak3[0])
    ? (streak3[0] > 0 ? 'T1' : 'T2') : null;
  return {
    momentum  : mom,
    eco_t1    : _ecoState(rounds1 || 0, total),
    eco_t2    : _ecoState(rounds2 || 0, total),
    streak,
    ring_size : ring.length
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────
module.exports = {
  ACTIVE_MAPS,
  computeMapAdvantage,
  fetchHighlights,
  fetchTeamStickers,
  findTeamSticker,
  findMatchHighlights,
  fetchCsApiMatches,
  fetchCsApiRankings,
  computeMapOverModel,

  fetchMatchVeto,
  computeLiveMomentum,
  fetchCsApiPlayerStats,
  buildTeamForm,
  buildH2H,
  loadHltvMapStats,
  buildMatchEnrichment,

  invalidateCache() { _cs2Cache.ts = 0; },
  _getCacheStatus() { return _cs2Cache.bsd_status || (_cs2Cache.data && _cs2Cache.data.length > 0 ? 'ok' : 'pending'); },

  async getCs2Matches(apiKey) {
    if (!apiKey) {
      console.warn('[CS2Service] BSD_API_KEY absent — CS2 feed disabled');
      return [];
    }
    if (Date.now() - _cs2Cache.ts < CS2_BSD_TTL_MS) return _cs2Cache.data;
    if (_cs2Fetching) return _cs2Cache.data; // anti-concurrent burst guard

    _cs2Fetching = true;
    try {
      // Parallel: live matches + upcoming (notstarted) + predictions
      const [resLive, resUpcoming, predMap] = await Promise.all([
        _bsdCs2('/api/v2/matches/live/', apiKey).catch(() => null),
        _bsdCs2('/api/v2/matches/?status=notstarted&limit=100', apiKey).catch(() => null),
        _fetchPredictions(apiKey)
      ]);

      // Detect addon not activated (401/403)
      const authError = [resLive, resUpcoming].find(r => r && (r.status === 401 || r.status === 403));
      if (authError) {
        console.warn(`[CS2Service] BSD CSGO addon non activé — HTTP ${authError.status}`);
        _cs2Cache = { ts: Date.now(), data: [], bsd_status: 'disabled', bsd_http: authError.status };
        return [];
      }

      const raw = [];
      for (const res of [resLive, resUpcoming]) {
        if (!res || res.status !== 200 || !res.data) continue;
        const items = Array.isArray(res.data)          ? res.data
                    : Array.isArray(res.data.results)  ? res.data.results
                    : [];
        raw.push(...items);
      }

      // Fallback: generic list if both empty
      if (raw.length === 0) {
        const res = await _bsdCs2('/api/v2/matches/?limit=100', apiKey).catch(() => null);
        if (res && res.status === 200 && res.data) {
          const items = Array.isArray(res.data.results) ? res.data.results
                      : Array.isArray(res.data)         ? res.data
                      : [];
          raw.push(...items);
        }
      }

      // Normalize + attach predictions (pass HLTV map stats for Map Advantage)
      const mapStats = loadHltvMapStats();
      const matches = raw.map(m => _normalizeMatch(m, predMap[String(m.id)] || null, mapStats));

      // Attach HLTV rankings from local JSON file (fallback)
      const hltvR = _loadHltvRankings();
      for (const m of matches) {
        const r1 = hltvR[m.team1.name.toLowerCase()];
        const r2 = hltvR[m.team2.name.toLowerCase()];
        m.team1.hltv_rank = r1 ? r1.rank : null;
        m.team2.hltv_rank = r2 ? r2.rank : null;
      }
      // Attach BSD ELO (live, replaces stale HLTV file) — 1 bulk call per 6h
      try {
        const bsdTeams = await fetchBSDCs2Teams(apiKey);
        for (const m of matches) {
          const b1 = bsdTeams[m.team1.name.toLowerCase()];
          const b2 = bsdTeams[m.team2.name.toLowerCase()];
          if (b1) { m.team1.elo_rating = b1.elo_rating; m.team1.elo_peak = b1.elo_peak; m.team1._bsd_team_id = b1.id; }
          if (b2) { m.team2.elo_rating = b2.elo_rating; m.team2.elo_peak = b2.elo_peak; m.team2._bsd_team_id = b2.id; }
        }
      } catch (_) {}

      // Attach live momentum for in-progress matches (ring-buffer based)
      for (const m of matches) {
        if (m.is_live && m.round_score) {
          m.live_momentum = computeLiveMomentum(m.id, m.round_score.team1, m.round_score.team2);
        }
      }

      // Sort: live first → then by date
      matches.sort((a, b) => {
        if (a.is_live !== b.is_live) return a.is_live ? -1 : 1;
        if (a.scheduled && b.scheduled) return new Date(a.scheduled) - new Date(b.scheduled);
        return 0;
      });

      _cs2Cache = { ts: Date.now(), data: matches, bsd_status: 'ok', bsd_http: 200 };
      console.log(`[CS2Service] ${matches.length} matches (${matches.filter(m => m.is_live).length} live, ${Object.keys(predMap).length} predictions)`);
      return matches;

    } catch (e) {
      console.warn('[CS2Service] Fetch error:', e.message);
      return _cs2Cache.data || [];
    } finally {
      _cs2Fetching = false;
    }
  }
};
