import { db } from '@/lib/db'

const NOW = new Date()

const players = [
  // ── ATP ──────────────────────────────────────────────────────────────
  {
    slug: 'sinner-jannik',
    name: 'Sinner Jannik',
    wikipediaTitle: 'JannikSinner',
    gender: 'ATP',
    country: 'ITA',
    points: 13500,
    rank: 1,
    peakRank: 1,
    elo: 2320,
    eloRank: 1,
    eloHard: 2263,
    eloHardRank: 1,
    eloClay: 2216,
    eloClayRank: 1,
    eloGrass: 2088,
    eloGrassRank: 2,
    l5: 'LWWWW',
    l5WinRate: 0.8,
    l5DrTrend: -0.91,
    hardMatches: 308,
    hardWinPct: 0.815,
    hardDr: 1.28,
    hardSpw: 0.684,
    hardRpw: 0.404,
    hardHoldPct: 0.878,
    hardBreakPct: 0.278,
    clayMatches: 110,
    clayWinPct: 0.755,
    clayDr: 1.24,
    claySpw: 0.654,
    clayRpw: 0.429,
    clayHoldPct: 0.828,
    clayBreakPct: 0.335,
    grassMatches: 39,
    grassWinPct: 0.744,
    grassDr: 1.28,
    grassSpw: 0.705,
    grassRpw: 0.379,
    grassHoldPct: 0.895,
    grassBreakPct: 0.219,
    compositeScore: 83.2,
  },
  {
    slug: 'alcaraz-carlos',
    name: 'Alcaraz Carlos',
    wikipediaTitle: 'CarlosAlcaraz',
    gender: 'ATP',
    country: 'ESP',
    points: 9960,
    rank: 2,
    peakRank: 1,
    elo: 2167,
    eloRank: 3,
    eloHard: 2198,
    eloHardRank: 2,
    eloClay: 2125,
    eloClayRank: 4,
    eloGrass: 2122,
    eloGrassRank: 1,
    l5: 'LWLWW',
    l5WinRate: 0.6,
    l5DrTrend: 0.15,
    hardMatches: 155,
    hardWinPct: 0.781,
    hardDr: 1.26,
    hardSpw: 0.672,
    hardRpw: 0.418,
    hardHoldPct: 0.865,
    hardBreakPct: 0.302,
    clayMatches: 80,
    clayWinPct: 0.763,
    clayDr: 1.22,
    claySpw: 0.638,
    clayRpw: 0.441,
    clayHoldPct: 0.825,
    clayBreakPct: 0.328,
    grassMatches: 28,
    grassWinPct: 0.786,
    grassDr: 1.27,
    grassSpw: 0.691,
    grassRpw: 0.392,
    grassHoldPct: 0.889,
    grassBreakPct: 0.221,
    compositeScore: 68.3,
  },
  {
    slug: 'zverev-alexander',
    name: 'Zverev Alexander',
    wikipediaTitle: 'AlexanderZverev',
    gender: 'ATP',
    country: 'GER',
    points: 7190,
    rank: 3,
    peakRank: 2,
    elo: 2104,
    eloRank: 5,
    eloHard: 2044,
    eloHardRank: 5,
    eloClay: 2089,
    eloClayRank: 3,
    eloGrass: 1985,
    eloGrassRank: 6,
    l5: 'LWWWW',
    l5WinRate: 0.8,
    l5DrTrend: 0.22,
    hardMatches: 385,
    hardWinPct: 0.745,
    hardDr: 1.14,
    hardSpw: 0.668,
    hardRpw: 0.372,
    hardHoldPct: 0.842,
    hardBreakPct: 0.245,
    clayMatches: 165,
    clayWinPct: 0.721,
    clayDr: 1.18,
    claySpw: 0.625,
    clayRpw: 0.401,
    clayHoldPct: 0.805,
    clayBreakPct: 0.302,
    grassMatches: 42,
    grassWinPct: 0.714,
    grassDr: 1.15,
    grassSpw: 0.652,
    grassRpw: 0.358,
    grassHoldPct: 0.821,
    grassBreakPct: 0.225,
    compositeScore: 81.0,
  },
  {
    slug: 'djokovic-novak',
    name: 'Djokovic Novak',
    wikipediaTitle: 'NovakDjokovic',
    gender: 'ATP',
    country: 'SRB',
    points: 3760,
    rank: 8,
    peakRank: 1,
    elo: null,
    eloRank: null,
    eloHard: 1500,
    eloHardRank: null,
    eloClay: 1500,
    eloClayRank: null,
    eloGrass: 1500,
    eloGrassRank: null,
    l5: 'LWWLL',
    l5WinRate: 0.4,
    l5DrTrend: -0.45,
    hardMatches: 520,
    hardWinPct: 0.823,
    hardDr: 1.31,
    hardSpw: 0.681,
    hardRpw: 0.425,
    hardHoldPct: 0.881,
    hardBreakPct: 0.295,
    clayMatches: 175,
    clayWinPct: 0.789,
    clayDr: 1.25,
    claySpw: 0.642,
    clayRpw: 0.438,
    clayHoldPct: 0.845,
    clayBreakPct: 0.318,
    grassMatches: 65,
    grassWinPct: 0.8,
    grassDr: 1.3,
    grassSpw: 0.698,
    grassRpw: 0.402,
    grassHoldPct: 0.892,
    grassBreakPct: 0.241,
    compositeScore: 74.7,
  },
  {
    slug: 'fritz-taylor',
    name: 'Fritz Taylor',
    wikipediaTitle: 'TaylorFritz',
    gender: 'ATP',
    country: 'USA',
    points: 3635,
    rank: 9,
    peakRank: 4,
    elo: null,
    eloRank: null,
    eloHard: 1500,
    eloHardRank: null,
    eloClay: 1500,
    eloClayRank: null,
    eloGrass: 1500,
    eloGrassRank: null,
    l5: 'LWWWW',
    l5WinRate: 0.8,
    l5DrTrend: 0.31,
    hardMatches: 245,
    hardWinPct: 0.653,
    hardDr: 1.1,
    hardSpw: 0.645,
    hardRpw: 0.358,
    hardHoldPct: 0.812,
    hardBreakPct: 0.215,
    clayMatches: 85,
    clayWinPct: 0.588,
    clayDr: 1.05,
    claySpw: 0.612,
    clayRpw: 0.365,
    clayHoldPct: 0.785,
    clayBreakPct: 0.258,
    grassMatches: 28,
    grassWinPct: 0.621,
    grassDr: 1.08,
    grassSpw: 0.635,
    grassRpw: 0.342,
    grassHoldPct: 0.798,
    grassBreakPct: 0.205,
    compositeScore: 71.5,
  },

  // ── WTA ──────────────────────────────────────────────────────────────
  {
    slug: 'sabalenka-aryna',
    name: 'Sabalenka Aryna',
    wikipediaTitle: 'ArynaSabalenka',
    gender: 'WTA',
    country: 'BLR',
    points: 9090,
    rank: 1,
    peakRank: 1,
    l5: 'WWWWW',
    l5WinRate: 1.0,
    l5DrTrend: 0.42,
    hardMatches: 220,
    hardWinPct: 0.782,
    hardDr: 1.25,
    hardSpw: 0.668,
    hardRpw: 0.415,
    hardHoldPct: 0.855,
    hardBreakPct: 0.282,
    clayMatches: 95,
    clayWinPct: 0.745,
    clayDr: 1.18,
    claySpw: 0.625,
    clayRpw: 0.401,
    clayHoldPct: 0.805,
    clayBreakPct: 0.302,
    grassMatches: 35,
    grassWinPct: 0.751,
    grassDr: 1.22,
    grassSpw: 0.652,
    grassRpw: 0.385,
    grassHoldPct: 0.832,
    grassBreakPct: 0.258,
    compositeScore: 89.7,
  },
  {
    slug: 'rybakina-elena',
    name: 'Rybakina Elena',
    wikipediaTitle: 'ElenaRybakina',
    gender: 'WTA',
    country: 'KAZ',
    points: 8143,
    rank: 2,
    peakRank: 3,
    l5: 'WWWWW',
    l5WinRate: 1.0,
    l5DrTrend: 0.18,
    hardMatches: 195,
    hardWinPct: 0.725,
    hardDr: 1.22,
    hardSpw: 0.675,
    hardRpw: 0.382,
    hardHoldPct: 0.848,
    hardBreakPct: 0.255,
    clayMatches: 78,
    clayWinPct: 0.682,
    clayDr: 1.12,
    claySpw: 0.618,
    clayRpw: 0.365,
    clayHoldPct: 0.782,
    clayBreakPct: 0.268,
    grassMatches: 32,
    grassWinPct: 0.785,
    grassDr: 1.28,
    grassSpw: 0.702,
    grassRpw: 0.368,
    grassHoldPct: 0.885,
    grassBreakPct: 0.212,
    compositeScore: 78.5,
  },
  {
    slug: 'swiatek-iga',
    name: 'Swiatek Iga',
    wikipediaTitle: 'IgaSwiatek',
    gender: 'WTA',
    country: 'POL',
    points: 6733,
    rank: 3,
    peakRank: 1,
    l5: 'WWWWW',
    l5WinRate: 1.0,
    l5DrTrend: 0.55,
    hardMatches: 185,
    hardWinPct: 0.768,
    hardDr: 1.28,
    hardSpw: 0.652,
    hardRpw: 0.428,
    hardHoldPct: 0.835,
    hardBreakPct: 0.305,
    clayMatches: 110,
    clayWinPct: 0.825,
    clayDr: 1.35,
    claySpw: 0.638,
    clayRpw: 0.452,
    clayHoldPct: 0.828,
    clayBreakPct: 0.352,
    grassMatches: 30,
    grassWinPct: 0.725,
    grassDr: 1.18,
    grassSpw: 0.625,
    grassRpw: 0.375,
    grassHoldPct: 0.805,
    grassBreakPct: 0.248,
    compositeScore: 89.6,
  },
  {
    slug: 'pegula-jessica',
    name: 'Pegula Jessica',
    wikipediaTitle: 'JessicaPegula',
    gender: 'WTA',
    country: 'USA',
    points: 6056,
    rank: 4,
    peakRank: 3,
    l5: 'WWWWW',
    l5WinRate: 1.0,
    l5DrTrend: 0.12,
    hardMatches: 210,
    hardWinPct: 0.685,
    hardDr: 1.15,
    hardSpw: 0.638,
    hardRpw: 0.362,
    hardHoldPct: 0.805,
    hardBreakPct: 0.228,
    clayMatches: 75,
    clayWinPct: 0.625,
    clayDr: 1.08,
    claySpw: 0.605,
    clayRpw: 0.358,
    clayHoldPct: 0.772,
    clayBreakPct: 0.245,
    grassMatches: 28,
    grassWinPct: 0.652,
    grassDr: 1.1,
    grassSpw: 0.628,
    grassRpw: 0.345,
    grassHoldPct: 0.788,
    grassBreakPct: 0.215,
    compositeScore: 80.0,
  },
  {
    slug: 'gauff-coco',
    name: 'Gauff Coco',
    wikipediaTitle: 'CocoGauff',
    gender: 'WTA',
    country: 'USA',
    points: 4879,
    rank: 7,
    peakRank: 2,
    l5: 'LWWWW',
    l5WinRate: 0.8,
    l5DrTrend: 0.25,
    hardMatches: 190,
    hardWinPct: 0.712,
    hardDr: 1.18,
    hardSpw: 0.645,
    hardRpw: 0.385,
    hardHoldPct: 0.822,
    hardBreakPct: 0.258,
    clayMatches: 85,
    clayWinPct: 0.685,
    clayDr: 1.15,
    claySpw: 0.615,
    clayRpw: 0.372,
    clayHoldPct: 0.795,
    clayBreakPct: 0.265,
    grassMatches: 30,
    grassWinPct: 0.682,
    grassDr: 1.12,
    grassSpw: 0.632,
    grassRpw: 0.355,
    grassHoldPct: 0.802,
    grassBreakPct: 0.228,
    compositeScore: 75.5,
  },
]

async function seed() {
  console.log(`Seeding ${players.length} players…`)

  for (const p of players) {
    const result = await db.player.upsert({
      where: { slug: p.slug },
      create: {
        ...p,
        metricsSource: 'tennisabstract',
        taScrapedAt: NOW,
        createdAt: NOW,
        updatedAt: NOW,
      },
      update: {
        name: p.name,
        wikipediaTitle: p.wikipediaTitle,
        gender: p.gender,
        country: p.country,
        points: p.points,
        rank: p.rank,
        peakRank: p.peakRank,
        elo: p.elo,
        eloRank: p.eloRank,
        eloHard: p.eloHard,
        eloHardRank: p.eloHardRank,
        eloClay: p.eloClay,
        eloClayRank: p.eloClayRank,
        eloGrass: p.eloGrass,
        eloGrassRank: p.eloGrassRank,
        l5: p.l5,
        l5WinRate: p.l5WinRate,
        l5DrTrend: p.l5DrTrend,
        hardMatches: p.hardMatches,
        hardWinPct: p.hardWinPct,
        hardDr: p.hardDr,
        hardSpw: p.hardSpw,
        hardRpw: p.hardRpw,
        hardHoldPct: p.hardHoldPct,
        hardBreakPct: p.hardBreakPct,
        clayMatches: p.clayMatches,
        clayWinPct: p.clayWinPct,
        clayDr: p.clayDr,
        claySpw: p.claySpw,
        clayRpw: p.clayRpw,
        clayHoldPct: p.clayHoldPct,
        clayBreakPct: p.clayBreakPct,
        grassMatches: p.grassMatches,
        grassWinPct: p.grassWinPct,
        grassDr: p.grassDr,
        grassSpw: p.grassSpw,
        grassRpw: p.grassRpw,
        grassHoldPct: p.grassHoldPct,
        grassBreakPct: p.grassBreakPct,
        compositeScore: p.compositeScore,
        metricsSource: 'tennisabstract',
        taScrapedAt: NOW,
        updatedAt: NOW,
      },
    })
    console.log(`  ✓ ${result.slug}`)
  }

  const count = await db.player.count()
  console.log(`\nDone. ${count} players in DB.`)
}

seed()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => db.$disconnect())